### ISSUE TITLE
Error Code MD4010 when registering application

### ISSUE THREAD

**Issue by byzosoftware** [amzn/selling-partner-api-docs#713] opened 2021-05-09 09:47 UTC
Hi,

when doing the OAuth Login I'm getting Error Code MD4010.

What does it mean?
How can I solve that?

Thank you,
Anton

**Comment by nodisk8800** [comment] 2021-05-10 01:50
if your application create in NA, you must login to NA site(https://sellingpartnerapi-na.amazon.com),
and your seller account must registered in NA.

**Comment by byzosoftware** [comment] 2021-05-10 07:47
The application has been created in europe and the seller account is registered in europe. The correspoding sites/urls are beeing used.

Thank you for info. Good to know.,

**Comment by nodisk8800** [comment] 2021-05-10 08:43
I run order/report/feeds.... api ,all are success.

if any problem in IAM config?

**Comment by byzosoftware** [comment] 2021-05-10 09:50
I was carefully following the instructions while creating the IAM config. Everything should be fine with it.

I suspect that there is a issue with the developer account. There haven't been any sales on that account for quite a while. Maybe it's related to that. There is also an SPDC300 Error when editing the app offer within sellercentral. That's why I suspect an issue with the developer account, although the developer account works fine with MWS.

**Comment by ShivikaK** [comment] 2021-05-11 22:30
Hello @byzosoftware 

Thank you for raising this issue.

Can you please provide us details regarding your application such as application ID and the OAuth authorization URI constructed to initiate OAuth workflow?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by byzosoftware** [comment] 2021-05-12 07:06
Hello Shivika,

Thank you for you answer!

This is the URI:
https://sellercentral.amazon.de/apps/authorize/confirm/amzn1.sp.solution.464d3d80-8254-4e93-be59-ffd447471ba1?amazon_state=MTYyMDc0NTA5MTA1Mu-_vQta77-977-977-9be-_ve-_ve-_vTIdMO-_vShZMO-_ve-_ve-_vQbvv70y77-977-9Gu-_vQk8ce-_ve-_vXPvv7065aKD77-9GF8fbHrvv70WBe-_vXvvv70b77-9Cu-_vUku77-977-977-977-977-9J--_ve-_vQ==&state=teststate-43262436saf&version=beta

App ID: amzn1.sp.solution.464d3d80-8254-4e93-be59-ffd447471ba1

I have also created a ticket within sellercentral sellersupport (6998073542).

Anton

**Comment by JosueExsim** [comment] 2021-05-13 15:14
Hi.
I have the same problem, could you please help me.

App ID: amzn1.sp.solution.6d2821df-1dbc-428c-8d46-815ed78d6d6d
Error Code: MD4010

**Comment by byzosoftware** [comment] 2021-05-17 14:43
Hello @ShivikaK ,

any news about this?

Thanks,
Anton

**Comment by ShivikaK** [comment] 2021-05-17 18:23
Hello @byzosoftware 

The case is currently being reviewed by Support and you should receive an update on the case soon.

Please continue monitoring the case for updates.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by xbaha** [comment] 2021-05-29 08:34
Hello, May i ask how to generate amazon state??
Thanks

**Comment by liangz98** [comment] 2021-06-03 07:08
hi,
Is there a solution now?

**Comment by ShivikaK** [comment] 2021-06-03 20:40
Hello everyone,

Apologies for the delay in response.

The issue has been reported to the engineering team and I will get back to you with a detailed update once we identify the root cause.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by byzosoftware** [comment] 2021-06-04 08:32
Hi @xbaha 
> Hello, May i ask how to generate amazon state??

The amazon state is passed by amazon as parameter in the url when it calls your URI. No need to generate it.
Anton

**Comment by ahmedmasmou** [comment] 2021-06-15 15:04
Hey @byzosoftware , any news about the issue?

**Comment by byzosoftware** [comment] 2021-06-15 15:46
Hi @ahmedmasmou ,
the MD4010 seems to be an issue with the seller account. With another seller account it is working.

Unfortunately we still have an unresolved Unauthorized error - like many others too:

```
{
"errors": [
{
"message": "Access to requested resource is denied.",
"code": "Unauthorized",
"details": ""
}
]
}
```
Attaching a inline policy for STS to the role like suggested in other posts, didn't help.

We have opend a Ticket (6998073542), but no answer/solution yet.

@ShivikaK 
Can you help?

Anton

**Comment by justin-xean** [comment] 2021-06-16 07:07
Hi.
I have the same problem, could you please help me.

**Comment by ShivikaK** [comment] 2021-06-16 17:55
Hello,

We reviewed the error code MD4010 and it appears the OAuth authorization URL constructed is not proper leading to this error. Please keep in mind any slight change by adding an additional '/' or missing out on '?' in the URL can lead to this error.

Can someone please share the OAuth URL being formed to confirm the same?

 Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by byzosoftware** [comment] 2021-06-16 18:03
Hello @ShivikaK 

there are 2 different issue:

1) MD4010

The error occurs only with our own seller/developer account, that we are required to use for development.

With another seller account it's working. But we can't use that for development.

So it's clearly related to the account 

2) Idependet of that there is an authorization error.

This occurs when we use self authorization and access amazon.nl. 

Because of 1) we can't use amazon.de with our account.

Anton

**Comment by ShivikaK** [comment] 2021-06-16 18:13
Hello @byzosoftware 

I noticed this URI was shared by you - https://sellercentral.amazon.de/apps/authorize/confirm/amzn1.sp.solution.464d3d80-8254-4e93-be59-ffd447471ba1?amazon_state=MTYyMDc0NTA5MTA1Mu-_vQta77-977-977-9be-_ve-_ve-_vTIdMO-_vShZMO-_ve-_ve-_vQbvv70y77-977-9Gu-_vQk8ce-_ve-_vXPvv7065aKD77-9GF8fbHrvv70WBe-_vXvvv70b77-9Cu-_vUku77-977-977-977-977-9J--_ve-_vQ==&state=teststate-43262436saf&version=beta

The URL format is incorrect, it should be https://sellercentral.amazon.de/apps/authorize/consent?amzn1.sp.solution.464d3d80-8254-4e93-be59-ffd447471ba1&amazon_state=MTYyMDc0NTA5MTA1Mu-_vQta77-977-977-9be-_ve-_ve-_vTIdMO-_vShZMO-_ve-_ve-_vQbvv70y77-977-9Gu-_vQk8ce-_ve-_vXPvv7065aKD77-9GF8fbHrvv70WBe-_vXvvv70b77-9Cu-_vUku77-977-977-977-977-9J--_ve-_vQ==&state=teststate-43262436saf&version=beta

Can you try this and let me know if MD4010 error still persists? 

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ahmedmasmou** [comment] 2021-06-17 14:15
Hey @ShivikaK ,
Thank you very much for the support.
It worked for me but you just need to add 'application_id=' before the app id value in the URL. 
@byzosoftware you should try this.
Please update the documentation as the callback_uri is not the right URL to append the parameters to.
Thanks a lot again!

**Comment by ShivikaK** [comment] 2021-06-21 21:29
Hello @ahmedmasmou 

Thank you for confirming that the issue is resolved and for pointing out the missed application_id keyword in Authorization URL.

I would like to understand the confusion around the oauth workflow process described in our documentation as we do not state anywhere to append parameters to the callback_uri.

The steps to construct an oauth authorization URL are provided here where you are required to add the required parameters such as application ID and version=beta (as needed) -

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#constructing-an-oauth-authorization-uri

Based on the workflow being tested (Website or Marketplace Appstore), the Amazon callback URI generated is loaded into the browser after the seller consents to authorize your application and the URI is automatically appended with parameters as described in our developer guide. 

Please let me know if any steps of the workflow process are confusing which is leading to these errors and I will accordingly review the documentation to get it updated.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by MicheleItalia1** [comment] 2021-06-22 10:17
Hi.
I have the same problem, could you please help me.

App ID: amzn1.sp.solution.d94d88e6-b62a-426b-9414-ac836bc74ad8 Error Code: MD4010

My OAuth authorization URI is:
https://sellercentral-europe.amazon.com/apps/authorize/consent?application_id=amzn1.sp.solution.d94d88e6-b62a-426b-9414-ac836bc74ad8&version=beta

Amazon responses are: 

amazon_callback_uri = https://sellercentral-europe.amazon.com/apps/authorize/confirm/amzn1.sp.solution.d94d88e6-b62a-426b-9414-ac836bc74ad8
amazon_state = MTYyNDM1NjMwODc3MO-_vXYu77-977-9zaXvv73vv71yVXckTH_vv73vv71G77-9Je-_vVzvv70y77-977-9GVrvv73vv71n77-977-9DO-_vW9v1azvv73vv73vv73vv710bTvvv71577-977-9Ie-_vUTvv70_77-9Mu-_vXFNae-_vS8=
selling_partner_id = A7RR4LHUQDIC1

The process fail in step 3 'The selling partner signs into your website', try to call
https://sellercentral-europe.amazon.com/apps/authorize/confirm/amzn1.sp.solution.d94d88e6-b62a-426b-9414-ac836bc74ad8?amazon_state=MTYyNDM1NjMwODc3MO-_vXYu77-977-9zaXvv73vv71yVXckTH_vv73vv71G77-9Je-_vVzvv70y77-977-9GVrvv73vv71n77-977-9DO-_vW9v1azvv73vv73vv73vv710bTvvv71577-977-9Ie-_vUTvv70_77-9Mu-_vXFNae-_vS8=&state=7570226e-3593-48b9-ad3d-ca2422daca6f&version=beta

Thanks,
Michele

**Comment by gvart-sellics** [comment] 2021-06-24 13:59
same here ,exactly the same issue as @MicheleItalia1 has

**Comment by baran-ozer** [comment] 2021-06-24 16:58
we are experiencing the same issue as @MicheleItalia1 has

**Comment by chrisptang** [comment] 2021-06-28 08:41
same issue.

**Comment by murat-unluer** [comment] 2021-06-30 18:25
same issue, called amazon

**Comment by huybui-hubt** [comment] 2021-07-01 06:54
Hi @MicheleItalia1 can you try to call url with param redirect_url:

https://sellercentral-europe.amazon.com/apps/authorize/confirm/amzn1.sp.solution.d94d88e6-b62a-426b-9414-ac836bc74ad8?amazon_state=MTYyNDM1NjMwODc3MO-_vXYu77-977-9zaXvv73vv71yVXckTH_vv73vv71G77-9Je-_vVzvv70y77-977-9GVrvv73vv71n77-977-9DO-_vW9v1azvv73vv73vv73vv710bTvvv71577-977-9Ie-_vUTvv70_77-9Mu-_vXFNae-_vS8=&state=7570226e-3593-48b9-ad3d-ca2422daca6f&version=beta&redirect_uri=<YOUR_OAUTH_CALLBACK_URI>

**Comment by chrisptang** [comment] 2021-07-02 06:41
> Hi.
> I have the same problem, could you please help me.
> 
> App ID: amzn1.sp.solution.d94d88e6-b62a-426b-9414-ac836bc74ad8 Error Code: MD4010
> 
> My OAuth authorization URI is:
> https://sellercentral-europe.amazon.com/apps/authorize/consent?application_id=amzn1.sp.solution.d94d88e6-b62a-426b-9414-ac836bc74ad8&version=beta
> 
> Amazon responses are:
> 
> amazon_callback_uri = https://sellercentral-europe.amazon.com/apps/authorize/confirm/amzn1.sp.solution.d94d88e6-b62a-426b-9414-ac836bc74ad8
> amazon_state = MTYyNDM1NjMwODc3MO-_vXYu77-977-9zaXvv73vv71yVXckTH_vv73vv71G77-9Je-_vVzvv70y77-977-9GVrvv73vv71n77-977-9DO-_vW9v1azvv73vv73vv73vv710bTvvv71577-977-9Ie-_vUTvv70_77-9Mu-_vXFNae-_vS8=
> selling_partner_id = A7RR4LHUQDIC1
> 
> The process fail in step 3 'The selling partner signs into your website', try to call
> https://sellercentral-europe.amazon.com/apps/authorize/confirm/amzn1.sp.solution.d94d88e6-b62a-426b-9414-ac836bc74ad8?amazon_state=MTYyNDM1NjMwODc3MO-_vXYu77-977-9zaXvv73vv71yVXckTH_vv73vv71G77-9Je-_vVzvv70y77-977-9GVrvv73vv71n77-977-9DO-_vW9v1azvv73vv73vv73vv710bTvvv71577-977-9Ie-_vUTvv70_77-9Mu-_vXFNae-_vS8=&state=7570226e-3593-48b9-ad3d-ca2422daca6f&version=beta
> 
> Thanks,
> Michele

The problem seems like to be in the step 3. I tried append `redirect_url` parameter to the URL in step 3: https://sellercentral- europe.amazon.com/apps/authorize/confirm/amzn1.sp.solution.xxx?selling_partner_id=xxx&amazon_state=xxx, it works.

How ever, this `redirect_url` parameter is marked as 'Optional' in the docs:


redirect_uri | A URI for redirecting the browser to your application. This must an OAuth Redirect URI that you specified when you registered your application. If you do not include the redirect_uri parameter, the default is the first OAuth Redirect URI that you specified when you registered your application.Optional
-- | --

**Comment by baran-ozer** [comment] 2021-07-02 08:40
thanks @chrisptang, it worked.

**Comment by MicheleItalia1** [comment] 2021-07-02 15:22
Thanks @christang,
It works!
The 'Selling Partner API Developer Guide' should be changed.

**Closed** 2022-06-10 18:46 UTC
Labels: bug, Researching, Auth&Auth, closed for inactivity
