### ISSUE TITLE
[FEATURE] Documentation How to  encrypt XML file and upload the Creat Feed Document use Python?

### ISSUE THREAD

**Issue by educatornum** [amzn/selling-partner-api-docs#389] opened 2021-02-08 05:45 UTC
I tried `GreatFeedDocument`, then I received a status code  is **200**, but get feed **`"processingStatus": "FATAL"`**
I have too many times tried but I can't understand,

How I can encrypt the XML file?

Here is my python script.

```python
from aws_auth import Auth
import requests
import json
from pprint import pprint
import base64, os
from Crypto.Util.Padding import pad
from Crypto.Cipher import AES
from Crypto.Hash import SHA256


ownercd = "****"
sp_auth = Auth(ownercd)


def pad(s):
    # Data will be padded to 16 byte boundary in CBC mode
    return s + b"\0" * (AES.block_size - len(s) % AES.block_size)


def getKey(password):
    # Use SHA256 to hash password for encrypting AES
    hasher = SHA256.new(password.encode())
    return hasher.digest()


# Encrypt message with password
def encrypt(message, key, iv, key_size=256):
    message = pad(message)
    cipher = AES.new(key, AES.MODE_CBC, iv)
    return iv + cipher.encrypt(message)


# Encrypt file
def encrypt_file(file_name, key, iv):
    # Open file to get file Data
    with open(file_name, "rb") as fo:
        plaintext = fo.read()
    # Encrypt plaintext with key has been hash by SHA256.
    enc = encrypt(plaintext, key, iv)
    # write Encrypted file
    with open(file_name + ".enc", "wb") as fo:
        fo.write(enc)
    return enc


if sp_auth != False:
    x_amz_access_token = sp_auth[0]  # AWS SP-api access token
    AWSRequestsAuth = sp_auth[1]  # AWS signature
    config = sp_auth[2]  # From mongo's config
    feed_headers = {
        "Content-Type": "application/json",
        "x-amz-access-token": x_amz_access_token,
    }
    contentType = {"contentType": "application/xml; charset=UTF-8"}
    # [1.1] Create a FeedDocument
    creat_feed_res = requests.post(
        config["BASE_URL"] + "/feeds/2020-09-04/documents",
        headers=feed_headers,
        auth=AWSRequestsAuth,
        data=json.dumps(contentType),
    )

    # [1.2] Store the response
    CreatFeedResponse = creat_feed_res.json()["payload"]
    feedDocumentId = CreatFeedResponse["feedDocumentId"]
    initializationVector = CreatFeedResponse["encryptionDetails"][ "initializationVector"]
    url = CreatFeedResponse["url"]
    key = CreatFeedResponse["encryptionDetails"]["key"]

    # [1.3] Upload and encrypt document
    filename = "carton.xml"
    iv = base64.b64decode(initializationVector)

    encrypt_data = encrypt_file(filename, getKey(key), iv)
    headers = {"Content-Type": "application/xml; charset=UTF-8"}
    res = requests.put(url, headers=headers, data=encrypt_data)

    print(res.status_code)  # 200
    print(res.request.body)  # b'8L^\xbeY\xf....
    print(res.content.decode())

```

`It is the GetFeed Response:`
![Screen Shot 2021-02-08 at 14 16 15](https://user-images.githubusercontent.com/25072337/107180385-ef840500-6a1b-11eb-8104-1c7e5fdba4ac.png)

Can anyone help me with that? Thanks in advance!

**Comment by johnkw** [comment] 2021-02-08 15:40
The lack of documentation is a duplicate of bug #363

**Comment by ritik-novostack** [comment] 2021-02-23 15:16
@educatornum please upload carton.xml

**Comment by educatornum** [comment] 2021-02-23 23:56
I solved the problem thank you @ritik-novostack  @johnkw

**Comment by ritik-novostack** [comment] 2021-02-24 06:19
@educatornum bro just for an example how to make an XML feed data file i want to see because i am working on that it will help me a lot if u just give me thank you

**Comment by educatornum** [comment] 2021-02-24 07:56
@ritik-novostack  Hi, 

1. You need an XML file
**IMPORTANT**: 5555 is my cartonID then i used the cartonId for _Get Labels_
here is my XML file, TYPE=> **POST_FBA_INBOUND_CARTON_CONTENTS** 
```xml
<?xml version="1.0" ?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
   <Header>
      <DocumentVersion>1.01</DocumentVersion>
      <MerchantIdentifier>ARI9W*****</MerchantIdentifier>
   </Header>
   <MessageType>CartonContentsRequest</MessageType>
   <Message>
      <MessageID>1</MessageID>
      <CartonContentsRequest>
         <ShipmentId>FBA15****</ShipmentId>
         <NumCartons>1</NumCartons>
         <Carton>
            <CartonId>5555</CartonId>
            <Item>
               <SKU>TEST-001</SKU>
               <QuantityShipped>1</QuantityShipped>
               <QuantityInCase>1</QuantityInCase>
            </Item>
         </Carton>
      </CartonContentsRequest>
   </Message>
</AmazonEnvelope>
```
2. You should the XML file encrypt with **Key** and **initialization vector** 
3. Upload the XML file to s3 and use the response  **URL** 

```python

dirname = os.path.dirname(os.path.abspath(__file__))
xmlFile_Name = dirname + "/template/carton.xml"

def encrypt(key, initializationVector):
    # Create random 16 bytes IV, Create 32 bytes key
    key = base64.b64decode(key)
    iv = base64.b64decode(initializationVector)

    # Encryption with AES-256-CBC
    if os.path.isfile(xmlFile_Name) == False:
        print("===== CARTON FILE NOT FOUND FROM ===== :  {}".format(xmlFile_Name))
        sys.exit()
    with open(xmlFile_Name, "r") as fo:
        plaintext = fo.read()
        # print(plaintext)
        encrypter = pyaes.Encrypter(pyaes.AESModeOfOperationCBC(key, iv))
        ciphertext = encrypter.feed(plaintext.encode("utf8"))
        ciphertext += encrypter.feed()
        res = requests.put(
            url,
            data=ciphertext,
            headers=contentType,
        )
        print("STATUS UPLOAD: ", res.status_code)  # 200
        if res.status_code == 200:
            print("===== FILE UPLOAD DONE =====")

# REQUEST 
feed_headers = {
    "Content-Type": "application/json",
    "x-amz-access-token": x_amz_access_token,
}
contentType = {"contentType": "application/xml; charset=UTF-8"}
creat_feed_res = requests.post(
        config["BASE_URL"] + "/feeds/2020-09-04/documents",
        headers=feed_headers,
        auth=AWSRequestsAuth,
        data=json.dumps(contentType),
    )
# [1.2] Store the response
CreatFeedResponse = creat_feed_res.json()["payload"]
feedDocumentId = CreatFeedResponse["feedDocumentId"]
initializationVector = CreatFeedResponse["encryptionDetails"][ "initializationVector"]
url = CreatFeedResponse["url"]
key = CreatFeedResponse["encryptionDetails"]["key"]

# print(feedDocumentId)
# print("KEY =>", key)
# print("IV    =>", initializationVector)
# print(url) #s3 url

contentType = {"Content-Type": "application/xml; charset=UTF-8"}
encryptFile = encrypt(key, initializationVector) 

# [3.1] Create a feed
feedType = "POST_FBA_INBOUND_CARTON_CONTENTS"
marketplaceIds = "A1VC38T7*****"
inputFeedDocumentId = feedDocumentId

createdFeedURL = "https://sellingpartnerapi-fe.amazon.com/feeds/2020-09-04/feeds"
createFeedBody = {
    "inputFeedDocumentId": inputFeedDocumentId,
    "feedType": feedType,
    "marketplaceIds": [marketplaceIds],
}
resCreatFeed = requests.post(
    createdFeedURL,
    headers=feed_headers,
    auth=AWSRequestsAuth,
    data=json.dumps(createFeedBody),
)
# time.sleep(15)
createFeedStatusCode = resCreatFeed.json()
if resCreatFeed.status_code == 202:
    # print("Steph 2).")
    feedId = createFeedStatusCode["payload"]["feedId"]
    print("FEED ID: ", feedId)

    # [3.2] CET a feed
    # time.sleep(10)
    getFeed = requests.get(
        config["BASE_URL"] +
        "/feeds/2020-09-04/feeds/{}".format(str(feedId)),
        headers=feed_headers,
        auth=AWSRequestsAuth,
    )

    # print("Steph 3).")
    # time.sleep(10)
    print("*"*50)
    print("RESPONE:")
    pprint(getFeed.json()['payload'])
    print("*"*50)
```

Here is my Get Feed response:
```
{'payload': {
       'createdTime': '2021-02-24T07:43:22+00:00',
       'feedId': '14795****',
       'feedType': 'POST_FBA_INBOUND_CARTON_CONTENTS',
       'marketplaceIds': ['A1VC38T7****'],
       'processingStatus': 'DONE'}
}
```

Then I used the cartonID, I can download the **get labels** PDF file's url


**PackageLabelsToPrint** is your cartonID you must set the CartonID here, for example: 
![Screen Shot 2021-02-24 at 16 49 20](https://user-images.githubusercontent.com/25072337/108965576-65e16200-76c0-11eb-8445-7859edcf3ffe.png)

Last,  I could download a PDF file using the URL
Here is my GetLabel:

![Screen Shot 2021-02-24 at 16 52 38](https://user-images.githubusercontent.com/25072337/108965888-ce304380-76c0-11eb-9929-46434e0686c2.png)

Good luck bro! If you have a question let me know.

**Comment by SouravPal95** [comment] 2021-07-14 13:42
Can we upload a json file instead of xml?

**Comment by johnkw** [comment] 2021-07-14 19:20
Similar to bug #363 - this has been deprecated entirely. The feeds_2020-09-04.md document should be updated to tell people in huge letters at the top to use the new version instead.

Note this is also a duplicate of bug #789.

**Comment by johnkw** [comment] 2021-07-14 21:08
@SouravPal95 see bug #881 for that request.

**Closed** 2022-06-10 18:41 UTC
Labels: Documentation, enhancement request, closed for inactivity
