### ISSUE TITLE
[BUG] Documentation How to createReport ??

### ISSUE THREAD

**Issue by PrashantMalaviya** [amzn/selling-partner-api-docs#912] opened 2021-06-19 17:29 UTC
Hello sir,@ShivikaK 

this is my code in python :-

auth = AWSRequestsAuth(aws_access_key="xxxx",
                           aws_secret_access_key="xxxx",
                           aws_host='sellingpartnerapi-na.amazon.com',
                           aws_region='us-east-1',
                           aws_service='execute-api')

endpoint = 'https://sellingpartnerapi-na.amazon.com/reports/2020-09-04/reports'
query = {"reportTypes":"GET_MERCHANT_LISTINGS_ALL_DATA",
      "marketplaceIds":"ATVPDKIKX0DER",
      "dataStartTime":"2020-01-01T00:00:24.000Z",

       }
headers = {"x-amzn-RequestId": "xxxx",
         "Content-Type": "application/json",
         'x-amz-access-token': TOKEN}
r = requests.post(endpoint, params=query, auth=auth, headers=headers)

output is :- 
{'errors': [{'code': 'InvalidInput',
               'message': 'One or more required parameters missing', 
                'details': 'marketplaceIds;reportType;'}]}

how TO sole this ????/

**Comment by johnkw** [comment] 2021-06-19 17:35
This API call works fine - your code is presumably just broken. In any case, without a complete HTTP log, there's nothing to go on. But this is not a bug report either way.

**Comment by PrashantMalaviya** [comment] 2021-06-19 17:57
Hello sir ,@johnkw 
Can you solve or any update my code mistakes ??

**Comment by ianrussel** [comment] 2021-06-20 04:21
@PrashantMalaviya this is working on my end
 

              [2021-06-20 04:19:01] local.INFO: https://sellingpartnerapi-eu.amazon.com/reports/2020-09-04/reports  
              [2021-06-20 04:19:01] local.INFO: {
                     "reportType": "GET_MERCHANT_LISTINGS_ALL_DATA",
                     "dataStartTime": "2021-06-20",
                     "dataEndTime": "2021-06-20",
                     "marketplaceIds": [
                          "A1805IZSGTT6HS"
                     ]
             }

**Comment by PrashantMalaviya** [comment] 2021-06-20 06:33
@ianrussel no sir it's not working....

**Comment by jamesp26** [comment] 2021-06-20 09:34
Have you changed your code yet? Its **reportType**, not reportTypes, and marketplaceIds needs to be an array.

**Comment by PrashantMalaviya** [comment] 2021-06-20 18:04
hello sir,@jamesp26

**Comment by johnkw** [comment] 2021-06-20 18:33
Please close this ticket. This is not a bug report. Open a stackoverflow discussion or something.

**Comment by PrashantMalaviya** [comment] 2021-06-20 19:11
can you send your email ,i send code in email in you ...and you checjk it?????
@johnkw

**Comment by ianrussel** [comment] 2021-06-21 03:45
Its POST so you may refactor your code like this

          >>> import json
          >>> payload = {'reportType": "GET_MERCHANT_LISTINGS_ALL_DATA", .........and aothers}
          requests.post(url, data=json.dumps(payload))

**Comment by PrashantMalaviya** [comment] 2021-06-21 04:03
thank you sir @ianrussel,it is working ....

**Closed** 2021-06-21 04:28 UTC
Labels: bug, documentation
