### ISSUE TITLE
OAuth authorization URI not working

### ISSUE THREAD

**Issue by aryatekpia** [amzn/selling-partner-api-docs#288] opened 2021-01-12 01:49 UTC
Our application uses SP-API

To allow our users to authorize they seller central account with our Application we have followed the guideline for website workflow.

So the users clicks on an authorize button on our application that will redirect them to:
https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.xxxxxxxx-xxxx-xxxxx-aa0e-352f2b01d9c2&state=57e6980c-9e70-4761-945f-ca4914cbff03

After clicking on this button the user is taken to seller central and after they login instead of seeing the consent page and redirecting back to our application they are getting a form that asks for our developer id.

this is not the behaviour described in the documentation and it is a blocker for our app because being a SP-API app we don't even have a developer id
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#website-workflow

**Comment by charliecode** [comment] 2021-01-12 02:01
@aryatekpia Is your app still in draft state? In other words, have you published it and been given approval by Amazon?

**Comment by aryatekpia** [comment] 2021-01-12 02:07
@charliecode yes our application status is published and it is listed and visible on amazon marketplace appstore

**Comment by charliecode** [comment] 2021-01-12 02:41
This is the first I'm hearing about this. In the event you can't find anything else then your best bet is prob opening a support case.

**Comment by aryatekpia** [comment] 2021-01-12 02:56
Yes I have opened up a support case but they said they will investigate the issue but now it is been more than 3 days and no response yet. and our application is in production and we are getting complains from users trying to register :(

here is the screenshot of the page we get instead of the consent page.

![screenshot](https://user-images.githubusercontent.com/63922709/104263539-c93c6b00-5457-11eb-82b3-301fc66f464f.png)

**Comment by 468092882** [comment] 2021-01-15 05:38
me too。。。。

**Comment by aryatekpia** [comment] 2021-01-15 05:47
> me too。。。。

Are you having the same issue? seeing this strange form instead of the consent page?

**Comment by 468092882** [comment] 2021-01-15 05:53
Yes, our situation is the same

**Comment by 468092882** [comment] 2021-01-15 05:54
> > 我也是....
> 
> 你有同样的问题吗？看到这种奇怪的形式，而不是同意页面？

Yes, our situation is the same

**Comment by aryatekpia** [comment] 2021-01-15 05:56
I have opened a case with Amazon 4 days ago and still no resolution...

**Comment by aryatekpia** [comment] 2021-01-15 19:51
@seanevan can you please advise ^ this shows that SP-API is clearly not ready for production and yet Amazon forced us to migrate to SP-API prior to publishing our application after two years of development with old MWS-API (they even refused to give us hybrid access). Is there anyway to escalate this? We are desperate for a resolution soon as our application is in production and live.

**Comment by seanevan** [comment] 2021-01-15 20:28
Hi @aryatekpia, Thanks for flagging this for me. Could you please share the case number you opened with support? I'll follow-up to figure out how to resolve this quickly for you.

Thanks,
Sean Evans
Manager, Support Engineering

**Comment by callumb123** [comment] 2021-01-15 20:30
> Hi @aryatekpia, Thanks for flagging this for me. Could you please share the case number you opened with support? I'll follow-up to figure out how to resolve this quickly for you.
> 
> Thanks,
> Sean Evans
> Manager, Support Engineering

I have just raised a support case for the exact same issue. My app was published a couple days ago. The case is 6709398252 if this is helpful.

**Comment by aryatekpia** [comment] 2021-01-15 20:47
@seanevan @callumb123 I really appreciate your help our case ID is 7850358671

**Comment by seanevan** [comment] 2021-01-15 20:56
Thanks @aryatekpia and @callumb123. I'm following up on both of your cases to expedite them.

**Comment by discover59** [comment] 2021-01-15 21:18
@aryatekpia I had same issue and I think it disappeared after I tried with 
`https://sellercentral.amazon.com/apps/authorize/consent?application_\id=amzn1.sellerapps.app.xxxxxxxx-xxxx-xxxxx-aa0e-352f2b01d9c2&state=57e6980c-9e70-4761-945f-ca4914cbff03&version=beta`.

It showed me MD1000 error and after removing `\` from `application_\id` it worked.

**Comment by 468092882** [comment] 2021-01-16 01:02
> 谢谢@aryatekpia和@ callumb123。我正在跟进您的两个案件，以加快处理速度。

Help me take a look, my case ID: 7525197991, thank you

**Comment by callumb123** [comment] 2021-01-16 09:17
> Thanks @aryatekpia and @callumb123. I'm following up on both of your cases to expedite them.

@seanevan Are you able to refer my case to someone who can actually help? I have raised 4 different issues with MWS support (as is always request by Amazon in these comments) and every single time without fail the first response I get has nothing to do with my actual question and just tells me that my MWS application has been approved and they close the case. It's as if they haven't even heard of SP-API!

I understand this won't be anything to do with you but I also thought I would mention this so you realise why many people are so reluctant to raise a case with support and instead post their issues here as it is the only way we are actually able to get any support.

I have reopened my case and asked support to re-read my question but I have little hope it will get a proper non copy and pasted response. Please help if you can as this is quite a serious issue.

**Comment by aryatekpia** [comment] 2021-01-16 16:19
Yeah another day passed and still no resolution :( they just replied asking again for the direct OAuth link which I had already provided them when I first opened this support case. I gave them the URL hoping this it would go to someone who can actually get it fixed.

**Comment by callumb123** [comment] 2021-01-18 11:20
> > Thanks @aryatekpia and @callumb123. I'm following up on both of your cases to expedite them.
> 
> @seanevan Are you able to refer my case to someone who can actually help? I have raised 4 different issues with MWS support (as is always request by Amazon in these comments) and every single time without fail the first response I get has nothing to do with my actual question and just tells me that my MWS application has been approved and they close the case. It's as if they haven't even heard of SP-API!
> 
> I understand this won't be anything to do with you but I also thought I would mention this so you realise why many people are so reluctant to raise a case with support and instead post their issues here as it is the only way we are actually able to get any support.
> 
> I have now had to reopen my case 4 times in the last few hours as support agents keep responding with totally unrelated answers and immediately closing the case. How can developers be expected to use this API when your suggested support method is less than useless? Its worse than getting blood from a stone.

@seanevan I am now on my 5 attempt at trying to get someone in support to look at this issue and give a response that has anything to do with my concern. Every time I have to reopen my case as they close it saying they don't look at appeals of registrations. Can you please provide some clarity as to why the support team only give default responses after making no attempt to read the actual issue and yet this is the recommended (and only) way to get bugs fixed? My entire application is at a standstill until this is fixed.

@aryatekpia Have you had any luck?

**Comment by aryatekpia** [comment] 2021-01-18 14:25
No still no response and the authorization url still does not redirect to consent screen. our application is at a standstill as well :(

**Comment by aryatekpia** [comment] 2021-01-19 19:07
Over 10 days and here is the response I got yesterday on my support case:

"Amazon Seller Support notes about the conversation:
We continue to research this issue and will update you as soon as any additional information is available. We apologize for the inconvenience this issue has caused."

This is starting to become ridiculous. They forced us to migrate to SP-API before launching our application live by refusing to grant us hybrid api access, and now the new API is clearly broken for over 10 days and they can not fix it. What are we supposed to tell our users? @seanevan

**Comment by ShivikaK** [comment] 2021-01-20 01:24
Hello @callumb123 and @aryatekpia,

We have received your support cases and a Support Engineer will reach out to you with next steps to help resolve the issue you are facing with OAuth workflow.

Thanks,
Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by ShivikaK** [comment] 2021-01-20 01:28
Hello @

> > 谢谢@aryatekpia和@ callumb123。我正在跟进您的两个案件，以加快处理速度。
> 
> Help me take a look, my case ID: 7525197991, thank you

Thank you for sharing the case ID. I will look into the case and someone will reach out to you via case on next steps to help resolve your issue.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by 468092882** [comment] 2021-01-20 02:27
> Hello @
> 
> > > 谢谢@aryatekpia和@ callumb123。我正在跟进您的两个案件，以加快处理速度。
> > 
> > 
> > Help me take a look, my case ID: 7525197991, thank you
> 
> Thank you for sharing the case ID. I will look into the case and someone will reach out to you via case on next steps to help resolve your issue.
> 
> Thanks,
>  Shivika Khare 
> Selling Partner API Developer Support

Hello, I am now modifying the application information to re-verify, and the following problems occurred when saving 
![0B26CDC9-0D56-46fb-AB16-E292E2D44B4A](https://user-images.githubusercontent.com/32814680/105118832-14b2e100-5b0a-11eb-9928-cced411409d4.png)

**Comment by ShivikaK** [comment] 2021-01-20 02:31
Hello @468092882 

Can you please open a support case for this issue so we can pursue the investigation. Please share the case ID once created and I will look into expediting your issue.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by 468092882** [comment] 2021-01-20 02:50
> Hello @468092882
> 
> Can you please open a support case for this issue so we can pursue the investigation. Please share the case ID once created and I will look into expediting your issue.
> 
> Thanks,
>  Shivika Khare 
> Selling Partner API Developer Support

Case ID : 7888069571，Please help me to check as soon as possible, my application development is suspended, waiting for a response, thank you

**Comment by callumb123** [comment] 2021-01-25 21:05
@ShivikaK Almost another week since this looked like it was getting dealt with and again things seem to have went quiet. Can you give any update on this and when we can expect it to be fixed?

I'm sure myself and @aryatekpia are not the only people who are losing business over this issue.

**Comment by ShivikaK** [comment] 2021-01-27 03:14
Hello,

For issues related to editing application, it has been resolved and you should be able to edit your app. Please mark the checkbox "Enable OAuth from Appstore" and save the app. Once completed, please submit the app listing again to be published.

**Comment by discover59** [comment] 2021-01-27 19:32
What's the difference between `OAuth Login URI` and `OAuth Redirect URI`?

**Comment by qqqcai** [comment] 2021-02-01 05:44
@ShivikaK 
HI~  I ran into the same problem. I don't have a developer id. 
The case is 7937726511. 
Thank you

**Comment by ShivikaK** [comment] 2021-02-02 19:56
> @ShivikaK
> HI~ I ran into the same problem. I don't have a developer id.
> The case is 7937726511.
> Thank you

Hello @qqqcai 

We have received your case and the case will be reviewed for application update changes. Once it is approved, please expect up to 10 days for the changes to be fully published. I will request reaching out via support cases for follow-ups.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by discover59** [comment] 2021-02-04 19:44
@ShivikaK Thanks for your explanation. My app is published and it's working without version=beta by marking the checkbox.

But redirect url doesn't return MWS auth token, though my app is hybrid app(SP and MWS).

**Comment by callumb123** [comment] 2021-02-04 20:14
> @ShivikaK Thanks for your explanation. My app is published and it's working without version=beta by marking the checkbox.
> 
> But redirect url doesn't return MWS auth token, though my app is hybrid app(SP and MWS).

@discover59 Just to let you know that the MWS token is not returned if you authorise yourself, you need to get someone else to try it and you should see it gets returned then. I was worried about the same thing but got someone else to try it and it was returned correctly. Hope that helps :)

**Comment by ShivikaK** [comment] 2021-02-04 20:18
Hello @discover59 ,

As mentioned above, if you are testing the oauth workflow for a self-auth scenario then the mws auth token is not returned. Hope this helps clarify the issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by discover59** [comment] 2021-02-04 20:22
@ShivikaK I cannot ask other seller to test my application before development is done. 😉 
This is not good for developers.

Is there any specific reason that it can't return mws token for self authentication? 
With MWS authentication, it returned mws auth token though it's self authentication.

**Comment by callumb123** [comment] 2021-02-04 20:27
@discover59 I agree it's not good for developers. I'm happy to test your workflow/URL if you wish to confirm the token is returned. It might not help for future testing but just for peace of mind as I know it frustrated me a lot!

**Comment by arvin915** [comment] 2021-02-28 03:57
> Hello,
> 
> For issues related to editing application, it has been resolved and you should be able to edit your app. Please mark the checkbox "Enable OAuth from Appstore" and save the app. Once completed, please submit the app listing again to be published. Please ensure if an app has already been submitted for publishing, you won't be able to edit the app till the updates are published.
> 
> All provided cases have been updated with next steps as well and I will request reaching out via support cases for follow-ups.
> 
> Please let me know if any new issues arise.
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support

Hello @ShivikaK,

I ran into the same problem.  The status of our app is Publised and I couldn't see the checkbox "Enable OAuth from Appstore" in Edit App page.

Please help me take a look. My case ID: 8045540371.

Thanks,
Arvin

**Comment by ShivikaK** [comment] 2021-03-01 18:31
Hello @arvin915 

The checkbox "Enable OAuth from Appstore" has been removed from the Edit App page and this functionality is now enabled by default when the application is submitted for publishing to Appstore.

Your support case is currently being reviewed. Please monitor the case for follow ups and next steps.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by Everestparts** [comment] 2021-03-12 20:34
@seanevan 

As of today I'm going on **35+ days** of dealing with support to get my issue resolved. 

I have been trying to link a self developed app to Seller Central and continuously receive an Access Denied error. I have followed the developer guide inside and out, tried STS authorization, tried ExecuteAPI directly to an IAM user. Nothing is working and seller support is lacking in the "support." 

All support says is "Please refer to the Developer Guide." without any reference as to what is causing the issue.

I am at a complete standstill with my company because I cannot gain simple access to my Seller Central. 

I need help, and so do a lot of others.

Thanks,

Ashton

**Comment by seanevan** [comment] 2021-03-13 00:35
Hi @Everestparts et al,

I have elevated this issue with our engineering team to address it as a top priority beginning on Monday morning. On behalf of the team here, I'm sorry for the delay in getting this resolved.

Best regards,
Sean Evans
Manager, Selling Partner API Developer Support

**Comment by Everestparts** [comment] 2021-03-15 14:39
Hi @seanevan 

Thank you, I have been at a complete standstill since trying to connect my application. Seller Support only refers sellers to the developer guide without any insight as to what can be causing the issue.

Regards,

Ashton

**Comment by Everestparts** [comment] 2021-03-22 13:26
@seanevan 

It has been another 10 days since I have received a response from Seller Support regarding Case ID 7999037991

I am in disbelief with how slow and unhelpful Seller Support is. My business is at a standstill because of this.

**Comment by garima-1297** [comment] 2021-04-08 14:20
Our application uses SP-API

To allow our users to authorize seller central account with our Application we have followed the guideline for website workflow.

So the users clicks on an authorize button on our application that will redirect them to consent page but it's opening only this url https://sellercentral.amazon.com/apps/authorize/consent? and showing this error Error Code: MD1000:
Why onclick application_id and state is not taking

**Comment by sidrafarooq** [comment] 2021-04-12 18:38
Application condition is Eraser what does it means ?

**Comment by pramohs** [comment] 2021-04-20 08:48
What is the point in having multiple redirect URLs configured in the app, if we are not able to use it? The redirection works only for the first entry.

**Comment by krithic15** [comment] 2021-04-20 17:42
> What is the point in having multiple redirect URLs configured in the app, if we are not able to use it? The redirection works only for the first entry.

Hello @pramohs, In order to choose from multiple redirect uris, kindly pass the redirect uri that you would like to use as query param along with the state token. I will request the team to update the documentation on how to multiple redirect uris.

Best,
Krithi,
Solutions Architect, SP API.

**Comment by pramohs** [comment] 2021-04-21 07:49
@krithic15 Hi, thanks for the reply. But i have already tried to do the same, but I'm always redirected to the First Redirect URL that is added in the APP Configuration, irrespective of the URL that I pass during exchange of LWA  Credentials. (My amazon SP-API App is in draft state.)

**Comment by krithic15** [comment] 2021-04-21 16:15
> @krithic15 Hi, thanks for the reply. But i have already tried to do the same, but I'm always redirected to the First Redirect URL that is added in the APP Configuration, irrespective of the URL that I pass during exchange of LWA Credentials. (My amazon SP-API App is in draft state.)

Hello @pramohs,
Can you please open a support case via https://developer.amazonservices.com/support and provide the app ID and oauth uri details you are using? A member from our support team should be able to assist you further with this issue.

Best,
Krithi,
Solutions Architect, SP API.

**Comment by slopeofhope81** [comment] 2021-05-14 19:26
HI  the redirect url doesn't return MWS auth token, though my app is hybrid app(SP and MWS). Do I need publish it in order to get the mws_token? I tested with two other seller's account.. but it's returning only spapi_oauth_code=ANPXXXXXX&state=1234&selling_partner_id=AXXXXXXX. could you please adivse?

Thanks for your work on this!!

**Comment by slopeofhope81** [comment] 2021-05-17 15:07
@seanevan @krithic15 could you help with my question above? thanks!

**Comment by slopeofhope81** [comment] 2021-05-17 15:07
@seanevan @krithic15 could you help with my question above? thanks!

**Comment by krithic15** [comment] 2021-05-17 17:00
Hello @slopeofhope81, 

For hybrid apps, you should be receiving both mws_token and spiapi_oauth_code when you authorize using version=beta before publishing as well. Can you please share your app ID?

Best,
Krithi,
Solutions Architect, SP API

**Comment by slopeofhope81** [comment] 2021-05-17 17:10
@krithic15 So looks I have missed that.  I did not finish authorizing the app because I thought that essentially meant publishing the app. If I authorize, my app will still work with the MWS API? I just want to make sure that is the case.
Thanks!

**Comment by krithic15** [comment] 2021-05-17 18:03
@slopeofhope81 Yes, that's correct. Authorizing a hybrid app in draft or published state will not affect your current MWS API call workflow.

Best,
Krithi,
Solutions Architect, SP API

**Comment by slopeofhope81** [comment] 2021-05-20 18:52
@krithic15 I just tested for my hybrid app. But I am not receiving mws_token.. This is my application_id: amzn1.sellerapps.app.083f9454-2663-4d72-a0c3-15a9cc692e28

thanks!

**Comment by krithic15** [comment] 2021-05-20 21:14
@slopeofhope81,

I have reached out to the concerned team. Will keep you posted. Thank you for your patience.

Best,
Krithi,
Solutions Architect, SP API

> @krithic15 I just tested my hybrid app. But I am not receiving mws_token.. This is my application_id: amzn1.sellerapps.app.083f9454-2663-4d72-a0c3-15a9cc692e28
> 
> thanks!

@slopeofhope81,

I have reached out to the concerned team to look into this. Will keep you posted. Thank you for your patience.

Best,
Krithi,
Solutions Architect, SP API

**Comment by slopeofhope81** [comment] 2021-05-21 19:09
@krithic15 
Hi could I get update? And let me know if there is anything on my end could help you out. But I think it should be a configuration issue on your end..

**Comment by krithic15** [comment] 2021-05-21 20:00
> @krithic15
> Hi could I get update? And let me know if there is anything on my end could help you out. But I think it should be a configuration issue on your end..

Hi @slopeofhope81,
Can I have the merchant ID on behalf of whom you performed the oauth handshake and also the timestamp?

Best,
Krithi,
Solutions Architect, SP API

**Comment by slopeofhope81** [comment] 2021-05-21 20:08
@krithic15 this is the merchant_id A2DUV77ZY92B2O and May 20th around 2:00PM EST. I can rerun the flow. let me know if the aforementioned is not sufficient.

**Comment by krithic15** [comment] 2021-05-21 20:46
> @krithic15 this is the merchant_id A2DUV77ZY92B2O and May 20th around 2:00PM EST. I can rerun the flow. let me know if the aforementioned is not sufficient.

@slopeofhope81 Thank you for the details. We were able to identify the issue on our end and have fixed it. Please try authorizing again and let us know if you still face issues.

Best,
Krithi,
Solutions Architect, SP API

**Comment by slopeofhope81** [comment] 2021-05-21 20:55
@krithic15 I just tested on my end and it works with that particular account. I will test with another seller's account once I get a hold of it next week. Also could you share what the issue was? I would appreciate that!  Thanks in advance!

**Comment by krithic15** [comment] 2021-05-21 22:19
> @krithic15 I just tested on my end and it works with that particular account. I will test with another seller's account once I get a hold of it next week. Also could you share what the issue was? I would appreciate that! Thanks in advance!

@slopeofhope81 It was a configuration issue in our back-end and I can confirm that it is not a user issue. Thank you for reporting this and apologies for the inconvenience caused!

Best,
Krithi,
Solutions Architect, SP API

**Comment by slopeofhope81** [comment] 2021-05-24 15:19
@krithic15 hi Did something reset again? mws_token is not coming back again..
Here is the config:
app_id
amzn1.sellerapps.app.083f9454-2663-4d72-a0c3-15a9cc692e28 and 
merchant_id
A2DUV77ZY92B2O 
and tested 11:15 EST.

**Comment by SouravPal95** [comment] 2021-07-05 16:26
I have created an endpoint that returns the OAuth URI. But upon visiting the URI, clicking on the confirm button does not do anything.

**Comment by ShivikaK** [comment] 2021-07-07 01:50
Hello @SouravPal95 

For confirm button to work correctly, you need to have both OAuth Login and Redirect URI information added to your application. Please verify if both details are added to your application by clicking on "Edit App".

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by SouravPal95** [comment] 2021-07-07 06:15
> Hello @SouravPal95
> 
> For confirm button to work correctly, you need to have both OAuth Login and Redirect URI information added to your application. Please verify if both details are added to your application by clicking on "Edit App".
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support

what should be the OAuth login URI?

**Comment by ShivikaK** [comment] 2021-07-07 17:17
> > Hello @SouravPal95
> > For confirm button to work correctly, you need to have both OAuth Login and Redirect URI information added to your application. Please verify if both details are added to your application by clicking on "Edit App".
> > Thanks,
> > Shivika Khare
> > Selling Partner API Developer Support
> 
> what should be the OAuth login URI? Unfortunately, I haven,t been able to locate this information in the DOCS

The OAuth Login URI defines the login page of your website during authorization. This URI is shown after a seller consents to authorize your application.

You can find such information in our new GitHub FAQS - https://github.com/amzn/selling-partner-api-docs/wiki/SP-API---General-FAQs (What are the Login and Redirect URI values to be added in OAuth information when I am registering my app?)

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by chrismeats** [comment] 2021-08-03 01:23
@krithic15 I have the same issue that slopeofhope81  was having in may. When I authorize an account I am not getting a mws_auth_token as part of the response. 
My App ID is:
amzn1.sellerapps.app.cc957e72-44a9-4a2a-aca8-28541a629dc1

Let me know if you are able to help?

**Comment by slopeofhope81** [comment] 2021-08-20 17:00
@krithic15 
I need your guidance! I have an application id amzn1.sellerapps.app.cc957e72-44a9-4a2a-aca8-28541a629dc1

when I tried to sign in via Oauth using the existing mws account (seller id =  A2DUV77ZY92B2O), it gave back the mws token and the selling partner id and oauth code but the new account (seller id = A74ZY3D03JB37) is throwing MD5100 error.

what could be the reason for the different results? 
This is my oauth url https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sellerapps.app.083f9454-2663-4d72-a0c3-15a9cc692e28&version=beta&state=07122340ecac65e7583e7fdc8dab87253e17622a25869729a2ab67a48c0bedc999fb2d2f%22

and finally, why is my app showing as suppressed? How do I update that?

Sincerely, 
Thanks

**Closed** 2022-11-19 00:27 UTC
Labels: Documentation, Auth&Auth, Support Issue, closing soon
