### ISSUE TITLE
messaging-api->confirmcustomizationdetails, return Invalid amazonOrderId and template combination

### ISSUE THREAD

**Issue by fengmiq** [amzn/selling-partner-api-docs#193] opened 2020-12-09 08:45 UTC
`curl -X POST "https://sellingpartnerapi-na.amazon.com/messaging/v1/orders/XXXX/messages/confirmCustomizationDetails?marketplaceIds=ATVPDKIKX0DER" -H  "accept: application/hal+json" -H  "Content-Type: application/json" -d "{  "text": "test"  }"`

I use https://sellingpartnerapi-na.amazon.com/messaging/v1/orders/xxx/messages/confirmCustomizationDetails?marketplaceIds=ATVPDKIKX0DER,send message fail,error:
Client error: `POST https://sellingpartnerapi-na.amazon.com/messaging/v1/orders/xxxxx/messages/confirmCustomizationDetails?marketplaceIds=ATVPDKIKX0DER` resulted in a `403 Forbidden` response: { "errors": [ { "code": "Unauthorized", "message": "Invalid amazonOrderId and template combination.", (truncated...) 

can you help me? can you supply one demo?

**Comment by ShivikaK** [comment] 2020-12-23 21:48
Hello @fengmiq 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks, 
Shivika Khare
 Selling Partner API Developer Support

**Comment by rugved1991** [comment] 2022-05-10 05:21
Hi @fengmiq,

If you are still seeing this issue, please provide us the case ID. We will investigate the issue further.
If the issue is resolved, please let us know and we will close the issue.

Best,
Rugved
Solutions Architect, SP API

**Comment by hanzhuzi** [comment] 2022-08-15 07:24
Hello, I also encountered this problem here, what is the cause? How can I fix this?

**Comment by EfeEnginC** [comment] 2022-08-26 09:16
This error cause of the order and template combination if you look at [https://developer-docs.amazon.com/sp-api/docs/messaging-api-v1-reference#getmessagingactionsfororder]  you should get which actions are allowed for specific order ID

**Comment by rugved1991** [comment] 2023-04-01 00:11
Hi,

@EfeEnginC is right. Please use the getMessagingActionsForOrder operation to check which message actions can be performed for a specific Order ID. Depending on the actions, you can send the appropriate message.
If you are still seeing the same issue, please open a developer support case for further investigation.

Best,
Rugved
Solutions Architect, SP API

**Closed by rugved1991** 2023-04-01 00:11 UTC
Labels: Support Issue
