### ISSUE TITLE
[BUG] getOrderItems API return a error json, the value of DeemedResellerCategory is not a string

### ISSUE THREAD

**Issue by NancyLin** [amzn/selling-partner-api-docs#970] opened 2021-07-01 09:21 UTC
We use the getOrderItems to get the response as follow:
```
{
"payload": {
	
			"AmazonOrderId": "302-XXXXXXX-XXXXXXX",
			"OrderItems": [
				{
				"ASIN": "B07PXXXXXX",
				"OrderItemId": "135XXXXXX35259"
						,"SellerSKU": "XXXX-XXXXXX-A"
											,"Title": "XXXXXXX"
											,"QuantityOrdered": 1
											,"QuantityShipped": 1
																,"ProductInfo": {
								"NumberOfItems": "1"
							}
											,"ItemPrice":{
			"CurrencyCode": "EUR",
			"Amount": "24.99"
			}
																					,"ItemTax":{
			"CurrencyCode": "EUR",
			"Amount": "3.99"
			}
																										,"PromotionDiscount":{
			"CurrencyCode": "EUR",
			"Amount": "0.00"
			}
											,"PromotionDiscountTax":{
			"CurrencyCode": "EUR",
			"Amount": "0.00"
			}
																										,"IsGift": "false"
																																									,"IsTransparency": false
																					,"DeemedResellerCategory": UOSS
										}			]
	}
} 
```

When we parse the JSON string to JSON, it returns the error that the "DeemedResellerCategory": UOSS is not a string.

**Comment by yfscret** [comment] 2021-07-01 09:39
the same error to me

**Comment by gopkg-dev** [comment] 2021-07-01 14:46
Our program also has this problem today, and the returned content is not a correct json format.

**Comment by cyrieu** [comment] 2021-07-01 17:42
Same problem as well - invalid JSON.

**Comment by NancyLin** [comment] 2021-07-02 01:59
The response returned by the getOrderItems API in the EU market and the Canadian market has this "invalid JSON" error. Is there anyone from Amazon who can reply?

**Comment by YFBook** [comment] 2021-07-02 02:14
+1

**Comment by leesenlen** [comment] 2021-07-02 06:46
Same problem as well - invalid JSON.

**Comment by wonsky87** [comment] 2021-07-02 07:10
Same problem as well - invalid JSON.

**Comment by tbatur** [comment] 2021-07-02 07:11
Same problem as well - invalid JSON (empty response)

**Comment by wonsky87** [comment] 2021-07-02 07:22
鬼佬什么时候修复。

**Comment by ShivikaK** [comment] 2021-07-02 18:23
Hello,

Thank you for raising this issue.

We are currently investigating this and I will get back to you with an update once we are able to identify the root cause for this potential bug.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by shailrshah** [comment] 2021-07-02 23:02
Do you still see the error?

**Comment by foxfiring** [comment] 2021-07-03 04:00
> Do you still see the error?

yes

**Comment by YFBook** [comment] 2021-07-05 02:34
orders after July 1st will have this error

**Comment by avvarga** [comment] 2021-07-07 17:58
Hello,

Thank you for your reports and your patience.

We have deployed a fix for this issue after identifying the error in our internal JSON response.

Thanks,
Alejandro Chavarria
Selling Partner API Developer Support

**Closed** 2021-07-15 17:23 UTC
Labels: bug, documentation
