### ISSUE TITLE
[BUG] x-amzn-RateLimit-Limit header is meaningless

### ISSUE THREAD

**Issue by bchecketts** [amzn/selling-partner-api-docs#848] opened 2021-06-08 20:06 UTC
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
The `x-amzn-RateLimit-Limit` is not easy to understand and does not seem to provide any meaningful information on how frequently requests are allowed

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md

**Description of what the documentation currently says**
Documentation describes the `x-amzn-RateLimit-Limit` as the number of requests per second allowed.  0.0055 would equate to only one request every 181 seconds (3 minutes!).  In practice, I'm after the 20-request (burst) is exhausted, I'm able to make about 1 request roughly every 6 seconds.  A Seller with nearly 10x the limit (0.045 instead of 0.0055) is able to make requests only slightly faster (1 request every 4.5 to 5 seconds).

**Description of what the documentation should say**
It feels like the documentation has no basis on what has really been implemented.  What has been implemented does not feel correct.

**Screenshots**
See our Solutions Architect for logs

**Additional context**
Testing this against what is supposed to be the "production" `/orders/v0/` endpoints.

**Comment by cgaugel** [comment] 2021-08-13 12:23
+1

**Comment by johnkw** [comment] 2022-04-16 20:30
This is a duplicate of https://github.com/amzn/selling-partner-api-docs/issues/86#issuecomment-911114383

**Closed** 2022-11-19 00:26 UTC
Labels: bug, Documentation, closing soon
