### ISSUE TITLE
Error MD5100 - Marketplace Appstore workflow

### ISSUE THREAD

**Issue by Patrick4** [amzn/selling-partner-api-docs#517] opened 2021-03-18 21:19 UTC
Hello,
My application is published this week and I am trying to access it through the Marketplace but it is giving me the following error MD5100. Can someone help me to understand what this error is?

**Comment by ShivikaK** [comment] 2021-03-23 01:43
Hello @Patrick4 

Thank you for raising this issue.

Can you attach a screenshot displaying the error along with your application ID?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by Veodin** [comment] 2021-04-06 14:13
We are seeing this same issue. Did you ever solve this Patrick?

![Capture3](https://user-images.githubusercontent.com/458797/113724773-97e7da00-96ea-11eb-94f8-e75afcd7c14f.PNG)

**Comment by ShivikaK** [comment] 2021-04-06 23:55
Hello @Veodin,

Can you share the case ID that was created when you submitted the app to be published?

**Comment by Veodin** [comment] 2021-04-07 00:00
The app is status is draft. It is not published yet. We are testing with
the version=beta parameter.

**Comment by ShivikaK** [comment] 2021-04-07 00:05
Hello @Veodin 

Can you share your app ID so we can review the configuration? Do you have OAuth information added to the application?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by Veodin** [comment] 2021-04-07 00:09
Hi  Shivika,

Yes, we have added the OAuth information to the application. The app ID is:
amzn1.sp.solution.32b659b9-c356-4351-ab0a-ea50e7b592b1

**Comment by ShivikaK** [comment] 2021-04-07 00:21
Hello @Veodin 

Your app setup looks proper. Can you share the OAuth authorization URL you constructed to test the workflow? Are you able to see the Consent page or does it throw an error prior to that?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by Veodin** [comment] 2021-04-07 01:23
https://sellercentral.amazon.co.uk/apps/authorize/consent?application_id=amzn1.sp.solution.32b659b9-c356-4351-ab0a-ea50e7b592b1&version=beta

We are able to see the consent page and amazon then redirects to our test web page correctly. It is after we send the user back to the callback URI that we receive the error message I posted above.

The callback URI that was generated during the last test we ran was:
https://sellercentral.amazon.co.uk/apps/authorize/confirm/amzn1.sp.solution.32b659b9-c356-4351-ab0a-ea50e7b592b1?redirect_uri=https://connector.alphalogix.co.uk/&amazon_state=MTYxNzc1ODI1Mjc4NDtj77-9O0Pvv71qQUrvv73Mq--_vX3vv70z77-9JMOeRcuK77-9Je-_vRBSWGdydO-_vQsO77-9Awfvv71425LPgu-_vcOo77-9B--_vRjvv73vv73ona9J77-977-9TDw=&state=TEST&version=beta

**Comment by ShivikaK** [comment] 2021-04-07 17:55
Hello @Veodin 

This is the OAuth information added to your application as per our record -

"loginurl": "https: //amazon.alphalogix.co.uk/account/amazon",
 "redirecturls": "https: //amazon.alphalogix.co.uk"

Is this correct? 

Additionally, it will be more convenient to work via a support case to resolve this issue. Please open a support case so we can further pursue the investigation.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by Patrick4** [comment] 2021-04-14 09:52
Hello,
My problem was in the consent url. The content was exchanged between 'amazon_state' and 'state'. After correcting this I already got access.

**Comment by pawan1793** [comment] 2021-04-20 10:24
hey @Patrick4  , I'm getting same error can u guide me what I'm doing wrong ?
this is my consent url
https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sp.solution.1b691271-ac77-4ec0-bcf8-56b4d7adf3c1&state=test&version=beta

**Comment by xslong** [comment] 2021-04-22 07:21
Hi, @ShivikaK  
 I have the same problem, is it solved? Thanks
![image](https://user-images.githubusercontent.com/5440930/115672490-324c4c80-a37e-11eb-816d-a62825c5c575.png)

**Comment by pawan1793** [comment] 2021-04-22 07:48
@xslong I got work around... changed api type to SP API .... SP API + MWS was not working 

![image](https://user-images.githubusercontent.com/8011942/115676498-489ddc80-a36d-11eb-8fdf-04da6cc936c6.png)

**Comment by xslong** [comment] 2021-04-22 09:20
Hello @pawan1793
Now the setting is SP API.

**Comment by xslong** [comment] 2021-04-23 09:17
> Hi, @ShivikaK
> I have the same problem, is it solved? Thanks
> ![image](https://user-images.githubusercontent.com/5440930/115672490-324c4c80-a37e-11eb-816d-a62825c5c575.png)

Found the reason, be sure to use other sellers for authorization.

**Comment by AmitMY** [comment] 2021-04-28 17:05
We are having the same issue DESPITE using a different sellers not defined with the authorization app.
![image](https://user-images.githubusercontent.com/5757359/116444106-aee69b80-a854-11eb-90c9-3a4edf8e6838.png)

**Comment by hrhearn7** [comment] 2021-05-04 19:23
@ShivikaK
Can you direct me as to what I need to put in the URI's?  Right now I am in draft state. Working through the "Marketplace Appstore Workflow"

In the OAuth Login URI - I have this - and it gets me to the consent page
https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sp.solution.5ba0226e-999f-4a49-8adf-bf8cd388bc6e&version=beta

But pressing the button comes back to the consent page.

What is the correct Value for **_"OAuth Redirect URI"_**? I put a value there now that is wrong because I was trying to test and now I cannot clear it out.

I need to try to publish this ASAP - but I want to get past this testing phase.  I do have a case ID8294325061

**Comment by charliecode** [comment] 2021-05-04 20:15
OAuth Login URI is for Marketplace Appstore Workflow. OAuth Redirect URI is for Website Workflow. I think you're getting the two confused. In the OAuth Login URI you'll put wherever you want a customer to be redirected to from the Marketplace Appstore, it should be the place they go to signup for your app but a little different than normal because it will already have the spapi_oauth_code in the redirect params. I'm fairly certain on this, it could be an error in the documentation from the looks of it at [Step 4. Amazon sends you the authorization information.](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#Step-4-Amazon-sends-you-the-authorization-information).

If I'm correct then the error is in this line: 

1. Amazon loads your **OAuth Redirect URI** into the browser (the first one you specified when you registered you application), adding the following query parameters:

It should say:

Amazon loads your **OAuth Login URI** into the browser (the first one you specified when you registered you application), adding the following query parameters:

**Comment by ShivikaK** [comment] 2021-05-05 20:57
Hello @hrhearn7 

The login URI is supposed to refer to the login page of your website during authorization. We recommend not to use the OAuth URL as login URI. 

The redirect URI is used to redirect the browser to your application after authorization to receive the oauth information i.e. the SP API OAuth code which is required to get the long term LWA Refresh token along with additional parameters Amazon returns.

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-amazon-sends-you-the-authorization-information

You can specify more than one redirect by including the redirect_uri parameter in the OAuth URL. If the redirect_uri parameter is not specified, it will default to the first OAuth Redirect URI you’ve defined during app registration. 

Hope this helps clarify the confusion.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by deepaktech94** [comment] 2021-06-14 18:03
@ShivikaK 

When new seller authorize our app we getting following error.

Error Code: MD5100

and some time blank page.

Our case is is - 8416319541 , can you please check the issue.@ShivikaK 

When new seller authorize our app we getting following error.

Error Code: MD5100

and some time blank page.

Our case is is - 8416319541 , can you please check the issue.

**Comment by ests** [comment] 2021-06-28 11:02
When you are debugging this particular issue it may be worth checking the "network" tab in dev tools. In my case there was one 400 request, and in the response payload you could see detailed error, f.i. "Invalid redirect URL received" was my cause of problem.

**Comment by WXinFfly** [comment] 2021-06-30 07:58
> Hello @hrhearn7
> 
> The login URI is supposed to refer to the login page of your website during authorization. We recommend not to use the OAuth URL as login URI.
> 
> The redirect URI is used to redirect the browser to your application after authorization to receive the oauth information i.e. the SP API OAuth code which is required to get the long term LWA Refresh token along with additional parameters Amazon returns.
> 
> https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-amazon-sends-you-the-authorization-information
> 
> You can specify more than one redirect by including the redirect_uri parameter in the OAuth URL. If the redirect_uri parameter is not specified, it will default to the first OAuth Redirect URI you’ve defined during app registration.
> 
> Hope this helps clarify the confusion.
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support

Hello. My app Id is amzn1.sellerapps.app.01bd19b4-07f6-47bd-97bc-c6d937760fd2. Why is this app under review? I opened a case in the store backstage and no one responded to me. What should I do?

**Comment by byzosoftware** [comment] 2021-07-01 20:29
@deepaktech94 
We are receiving the MD5100 error only when appending redirect_uri to the OAuth Url. If we don't specificy redirect_uri parameter everything works fine.

@ShivikaK 
Why is this? Is this a bug?

Anton

**Comment by ests** [comment] 2021-07-01 20:38
@byzosoftware if you don't specify redirect_uri it will take the one you've configured in seller central. If you specify redirect_uri then you must ensure that it matches one of the URLs (if you added more than one) that were added. So for example if you added `https://example.com/auth/callback` but used `&redirect_uri=http://example.com/auth/callback` (note no https) in a query or anything other then it will fail with MD5100

**Comment by ShivikaK** [comment] 2021-07-01 20:58
> > Hello @hrhearn7
> > The login URI is supposed to refer to the login page of your website during authorization. We recommend not to use the OAuth URL as login URI.
> > The redirect URI is used to redirect the browser to your application after authorization to receive the oauth information i.e. the SP API OAuth code which is required to get the long term LWA Refresh token along with additional parameters Amazon returns.
> > https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-amazon-sends-you-the-authorization-information
> > You can specify more than one redirect by including the redirect_uri parameter in the OAuth URL. If the redirect_uri parameter is not specified, it will default to the first OAuth Redirect URI you’ve defined during app registration.
> > Hope this helps clarify the confusion.
> > Thanks,
> > Shivika Khare
> > Selling Partner API Developer Support
> 
> Hello. My app Id is amzn1.sellerapps.app.01bd19b4-07f6-47bd-97bc-c6d937760fd2. Why is this app under review? I opened a case in the store backstage and no one responded to me. What should I do?

Hello @WXinFfly 

Please open a new issue for app publish queries as your question does not appear to be related to MD5100 error for which this github issue has been kept open.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment] 2021-07-01 21:00
> @deepaktech94
> We are receiving the MD5100 error only when appending redirect_uri to the OAuth Url. If we don't specificy redirect_uri parameter everything works fine.
> 
> @ShivikaK
> Why is this? Is this a bug?
> 
> Anton

Hello @byzosoftware 

As stated above, your redirect URI information should also be added to the application. Without specifying any redirect uri in OAuth URL, it directs it to the first URI added to the app. If you specify a redirect uri, the URI must match the URI added to the application.

Please let me know if issue still persists after making these corrections.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by byzosoftware** [comment] 2021-07-02 14:21
@ShivikaK 
we have added two url to the application. When we append one of the Urls as redirect_uri Parameter to the OAuth Url there is a MD5100 error. Only if we don't append the redirect_uri_Parameter it is working.

Seems to be a not intended behaviour?

Anton

**Comment by ShivikaK** [comment] 2021-07-02 19:28
Hello @byzosoftware 

It will be help me investigate this issue if you can share the OAuth authorization URL you have constructed which includes the redirect_uri parameter as well.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by Sellcon** [comment] 2021-07-28 13:52
Hello,

I am a developer and status of my app is published and I have third-party sellers connected to app. Type of my app is hybrid- MWS and SP-API. I had tried to use OAuth SP-API (now I use MWS) and I realized that I have to change my redirect_url. Could you tell me if I edit redirect_url my app will be pending again?
Thanks
I want to have published status and access all the time without reviewing.

**Comment by slopeofhope81** [comment] 2021-08-19 19:00
Hi @ShivikaK 

Could you help what the issue is? I spent about last three hours to debug but I am stilling getting MD5100. 

My app id is: amzn1.sellerapps.app.083f9454-2663-4d72-a0c3-15a9cc692e28

Error Code: MD5100

**Comment by sellershubio** [comment] 2021-12-28 13:53
Hello,

When we are trying to authorization in SP-API, we are getting the error: MD5100

 App ID: amzn1.sellerapps.app.d530fe78-51c0-4a4b-8ce3-38f5502d0e24

Error Code: MD5100

**Comment by juncai-pan** [comment] 2022-01-18 03:16
hello, I used SP Application to Auth, but get  a MD5100  result, like this
App ID: amzn1.sp.solution.15891a75-XXXXXXXXXXXX
Error Code: MD5100
we config the 'Auth redirect uri' of the application,
why we get this result(MD5100), 
we must marking the box "Enable OAuth from Appstore" in Edit App page?
Looking forward to your feedback, thank you。

**Comment by getvicky83** [comment] 2022-01-20 01:23
hello, 

I am also getting Error Code: MD5100
I have raised caselog have sent outhURL and chasing for days but havenot got any response.

my developer account is hybrid of MWS and SPAPI, if i try to authenticate the seller's account, it errors.
but if i try to authenticate our developer account it doesnot. 

My app id : amzn1.sp.solution.2809da35-8fb2-4b0e-bc05-e1d7e590c0a4

looks like lots of people are getting MD5100 error, Is amazon going to put some proper error description?

**Comment by getvicky83** [comment] 2022-01-25 15:04
my issues is resolved by engineering team. Looks like it was backend issue

**Comment by JungleBooks** [comment] 2022-01-28 15:56
Amazon's back-end? or your application's back-end?

**Comment by AbePerl1** [comment] 2022-02-08 16:29
Hello.

I am also getting the same error

App ID: amzn1.sp.solution.ebb92d36-2f9d-45e4-976c-14379ae1ad68

Error Code: MD5100

**Comment by getvicky83** [comment] 2022-02-08 16:30
> Amazon's back-end? or your application's back-end?

Amazon

**Comment by AbePerl1** [comment] 2022-02-08 16:36
As a few developers above mention is we leave the redirect uri empty it works

redirect_uri=&amazon_state

**Comment by getvicky83** [comment] 2022-02-08 20:50
> As a few developers above mention if we leave the redirect URI empty it works
> 
> redirect_uri=&amazon_state
whats your Outh URI look like

**Comment by a9korn** [comment] 2022-02-14 08:36
Hello, the same problem with Error Code: MD 5100,
in my case: my App was published and my own seller account got authorization normal, but each other got the error,
tried more ways, also with empty uri (redirect_uri=&amazon_state) but still does not work.
now I have opened case and waiting answer from Amazon.
if someone has solved this problem - post how you did it.

**Comment by ZenSergius** [comment] 2022-04-27 12:51
I had an error when a user tried to log in using `vendorcentral` URL: 
```
Something went wrong
We are sorry but we encountered an error while processing your request.

Please also ensure that application ID and version match those used at the start of the OAuth workflow. Ensure that your workflow adds the version=beta parameter to the Amazon callback URI to indicate that the workflow is for authorising an application in draft status.

Please contact Selling Partner Support and provide them with the following information:

App ID: <some app id>

Error Code: MD5100
```

The problem was solved when I checked the "Vendor" option on the application edit page:
![Screenshot from 2022-04-27 15-49-34](https://user-images.githubusercontent.com/16031099/165521764-79dcb1a7-2aa4-4dbf-8cfe-b42794110fdb.png)
Maybe this solution will help someone )

**Closed** 2022-11-19 00:26 UTC
Labels: bug, Documentation, closing soon
