### ISSUE TITLE
[BUG] listCatalogItems restore rate broken

### ISSUE THREAD

**Issue by callumb123** [amzn/selling-partner-api-docs#323] opened 2021-01-21 09:54 UTC
The documentation says that listCatalogItems has a restore rate of 1 per second (up from 1 per 5 seconds for MWS). I am able to send 1 request every second for about 15 seconds before it starts intermittently saying I have exceeded the restore rate. I have even tried spacing requests 2 or 3 seconds apart and the same thing happens.

Can anyone confirm if they have the same issue or have been able to continuously send listCatalogItems requests 1 second apart with no problem? I have already raised a support case (6673270062) but it has almost been 3 weeks and I am getting nowhere.

I decided to switch my entire application over to SP-API from MWS as I saw that the restore rate for listCatalogItems had increased and as this is an endpoint I use frequently I thought it would be worth it. Its disappointing to have went through the hassle of migrating to not see the expected benefits.

**Comment by ShivikaK** [comment] 2021-01-29 18:38
Hello @callumb123 

Thank you for raising this issue.

I am following up on your case to expedite the issue raised for resolution. 

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by callumb123** [comment] 2021-02-03 21:40
@ShivikaK is there any progress on this issue at all? I understand you said you were going to expedite my issue but it's been 3 weeks since the person who was originally assigned my support case has responded despite multiple chasers so would be nice to see at least some movement on it.

**Comment by ShivikaK** [comment] 2021-02-10 23:08
Hello @callumb123 

As we have the case opened with Support and the issue is being investigated, I will close this issue. We will update you via case on next steps.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by callumb123** [comment] 2021-02-21 08:55
@ShivikaK Can this issue be reopened as it has been 2 weeks with no update and my case has now been opened for 2 months and it seems it is no further forward. Please reopen this issue or provide me an update in the support case. This is a serious road blocker for my entire application.

**Comment by cgaugel** [comment] 2021-02-22 19:15
Why don't you answer @ShivikaK ?

**Comment by ShivikaK** [comment] 2021-02-22 19:27
Hello @callumb123 

The issue has been reported to our engineering team and the assigned Support Engineer will reach out to you with an update regarding the same. I will keep this issue open till we have the problem resolved.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by callumb123** [comment] 2021-02-22 19:53
@ShivikaK Thank you for reopening the case. I have received a response from the Support Engineer with an explanation however as far as I can tell this would not explain the scenario I am seeing. I have provided more request IDs so hopefully these will be useful to the engineers. Looking forward to hearing back from them soon. I will update here and close the issue as soon as it has been resolved.

**Comment by callumb123** [comment] 2021-03-02 07:36
Hi @ShivikaK,

Could you please chase up my support case? My case has now been opened for over 2 months and I am no closer to getting a solution. The release of my entire application has been on hold for 2 months now because of this issue.

**Comment by cgaugel** [comment] 2021-03-03 08:38
@callumb123 , you wont get any answer. They always say "the engeneering team is working on it".

**Comment by callumb123** [comment] 2021-03-06 22:44
@cgaugel It's sad how correct you are. Over 2 months since I first raised this pretty simple issue to still be told someone is working on it but they can't give me an ETA. If someone had genuinely been working on it for as long as they say there is no way they wouldn't have fixed the issue yet.

**Comment by callumb123** [comment] 2021-03-10 21:57
@ShivikaK @seanevan Can someone give me a valuable update on this or my support case (6673270062)?

I received one update that was not the issue I was seeing. Since then I have only received updates saying that it is being looked into but there is no ETA. My clients cannot use my app until this issue is fixed and they are asking for updates, I can't keep saying that I don't know when this will be fixed. This has been opened for over 2 months now with no sign of being fixed any time soon.

**Closed** 2022-06-10 18:40 UTC
Labels: Support Issue, closed for inactivity
