### ISSUE TITLE
Too Many Active Keys

### ISSUE THREAD

**Issue by xbaha** [amzn/selling-partner-api-docs#813] opened 2021-06-02 10:07 UTC
i am getting this content error:

```
&nbsp; | Name | Value | Type
-- | -- | -- | --
&nbsp; | Content | "{\n  \"errors\": [\n    {\n      \"message\": \"Too Many Active Keys\",\n      \"code\": \"InvalidInput\"\n    }\n  ]\n}" | string
```

The same call was working for days, suddenly I am getting this error on ALL my calls????

**Comment by yswenli** [comment] 2021-06-02 10:25
POST /reports/2020-09-04/reports
GET_FBA_FULFILLMENT_INBOUND_NONCOMPLIANCE_DATA
{
  "errors": [
    {
      "message": "Too Many Active Keys",
      "code": "InvalidInput"
    }
  ]
}

**Comment by billsquall** [comment] 2021-06-02 10:29
POST /reports/2020-09-04/reports
GET_FBA_FULFILLMENT_INBOUND_NONCOMPLIANCE_DATA
{
"errors": [
{
"message": "Too Many Active Keys",
"code": "InvalidInput"
}
]
}

me too

**Comment by xbaha** [comment] 2021-06-02 10:44
are you getting this for reports or everything?

**Comment by mainak777** [comment] 2021-06-02 11:09
I am facing the same issue for Orders API
"{\n  \"errors\": [\n    {\n      \"message\": \"Too Many Active Keys\",\n      \"code\": \"InvalidInput\"\n    }\n  ]\n}"
GET/orders/v0/orders

**Comment by RatebHabbab** [comment] 2021-06-02 13:06
I'm facing the same issue for the following APIs: order, catalog, inventory, sales and reports.

**Comment by edward-rafalovsky** [comment] 2021-06-02 13:58
> i am getting this content error:
> 
> ```
> &nbsp; | Name | Value | Type
> -- | -- | -- | --
> &nbsp; | Content | "{\n  \"errors\": [\n    {\n      \"message\": \"Too Many Active Keys\",\n      \"code\": \"InvalidInput\"\n    }\n  ]\n}" | string
> ```
> 
> The same call was working for days, suddenly I am getting this error on ALL my calls????

Same problem on all the types of requests, Feeds, Orders, etc

**Comment by brenjt** [comment] 2021-06-02 15:15
I had the same problem with all my API calls. I can't find any way to get around it or a way to revoke/delete old keys.

**Comment by moltar** [comment] 2021-06-02 15:49
We are getting the same across all regions.

**Comment by ganeshkrishnan1** [comment] 2021-06-02 16:15
Same error.  is anyone even looking at the errors? Our dev work is stuck and Amazon has given us till September to migrate from MWS

**Comment by isaacngordon** [comment] 2021-06-02 16:33
I'm experiencing this same issue. I have production code that has been running fine since my last deployment several weeks ago, and now all of a sudden I'm receiving "Too Many Active Keys" error message on all api calls.

**Comment by pprbhm** [comment] 2021-06-02 16:54
Hello,
Thank you for bringing up this issue as multiple people are facing it. Can @xbaha or @brenjt open a case with Developer Support team [here](https://developer.amazonservices.com/support) so that it can be worked on more detailed level.

**Comment by vicky-3001** [comment] 2021-06-02 17:03
Facing this issue for all api calls. This is strange, still no one is working on the fix

**Comment by xbaha** [comment] 2021-06-02 17:07
@pprbhm this issue is not related to me only, It's happening to many, so i don't think opening a case would do anything.

**Comment by pprbhm** [comment] 2021-06-02 17:11
> @pprbhm this issue is not related to me only, It's happening to many, so i don't think opening a case would do anything.

Hi @xbaha I understand that but without having to know requestID's, sellerID and their permissions, It's not possible to identify an error. Also i would not advise to put such details on Public forum hence suggested to open a case and we can take it from there, Once finding the error we can update the forum on it.

**Comment by xbaha** [comment] 2021-06-02 17:16
@pprbhm the issue is not related to a sellerId, requestId nor permissions, what used to work suddenly stopped for many on ALL API calls.
If Amazon is following Github bugs, they should do something, opening a case from my experience has a painful waiting for months without any actual results.

**Comment by pprbhm** [comment] 2021-06-02 17:52
Hello @xbaha Some issues are seller/vendor specific so that needs a personal attention. I am sorry to hear you had bad experience with case with developer support team. The currently discussed issue is identified and backend team is working on fix for it.

**Comment by xbaha** [comment] 2021-06-02 17:54
@pprbhm Thanks for the update!

**Comment by ganeshkrishnan1** [comment] 2021-06-02 18:06
I have raised a request with the request id, time stamp and path.

I always dread raising requests on Amazon. Their response is always something like "can you please provide additional data including moon phase and chair taste when you submitted this request"

**Comment by jhullparkseed** [comment] 2021-06-02 18:22
Though I opened a similar but different thread I'll jump in here to track.  I agree that it seems more a general bug/error since yesterday all was good and today not.  With an official announcement from Amazon on MWS, there is pressure to change and I'd feel better switching to an API that is either stable or the developers are quick to follow up.  Glad to read a team is on it.

**Comment by parvathm** [comment] 2021-06-02 19:17
Hi all,

This issue is resolved. Please try making a request and let us know if you are still facing same issue.
Sorry for the inconvenience caused.

Thanks,
Parvathm,
Selling Partner API Developer Support.

**Comment by xbaha** [comment] 2021-06-02 19:20
@parvathm Thanks for the quick response, it's resolved for me.

**Comment by brenjt** [comment] 2021-06-02 19:21
It's working for me too. Thank you!

**Comment by jhullparkseed** [comment] 2021-06-02 19:59
me too.  whew!

**Comment by FloderCC** [comment] 2021-06-15 20:07
Me too. Please help.

**Comment by glukoid** [comment] 2021-06-15 21:21
no line of code of my application was changed but suddenly I got the same error:

{
  "errors": [
    {
      "message": "Too Many Active Keys",
      "code": "InvalidInput"
    }
  ]
}

if anyone could help me to understand what this error about and how to solve it.

**Comment by parvathm** [comment] 2021-06-15 21:37
Hi @glukoid,

"Too Many Active Keys" is due to a issue on our end. We are actively working to fix it. I will update once the issue is resolved.

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by ShivikaK** [comment] 2021-06-15 22:58
Hello everyone,

The issue causing "Too Many Active Keys" has been resolved and you should be able to make a successful request. Please let us know if error persists.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by moltar** [comment] 2021-06-16 00:02
Has it been fixed permanently or should we create defence code for it in the future? @ShivikaK

**Comment by ShivikaK** [comment] 2021-06-16 19:40
Hello @moltar 

We are currently fully investigating the root cause and working on fixing this issue permanently. If the error starts occurring in the meantime, please update here or notify us via Support case.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by traceremick** [comment] 2021-06-23 18:02
@ShivikaK started receiving this error today for the first time. Anything we can do on our end to resolve this issue?

**Comment by ShivikaK** [comment] 2021-06-23 18:13
Hello @traceremick 

Are you receiving the Too Many Active Keys exception or is it a different error message?

Could you share some more details regarding this?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by traceremick** [comment] 2021-06-23 18:23
> Hello @traceremick
> 
> Are you receiving the Too Many Active Keys exception or is it a different error message?
> 
> Could you share some more details regarding this?
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support

Apologies for lack of supporting info.

I was receiving the same exception, "Too Many Active Keys" for at least an hour today while accessing the catalog api. Though it appears to be fixed now with no changes on my end.

**Comment by ShivikaK** [comment] 2021-06-23 18:41
Hello @traceremick 

Thank you for providing the details. The team is investigating the cause for the errors as the issue was fixed and should not have occurred again.

If you start getting the error again, please share the timestamp of the first such request and which API you were trying to access.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by jhullparkseed** [comment] 2021-06-23 19:48
With such a quick response  can we also look at the Authorization errors that many people are having  with the FEEDS apis.  I can, for example  use ORDERS like getOrder just fine and yet createDocumentFeed gives me an error using the same authentication steps.  I've put a support case in (ID8494311371) but have gotten no real response and I have provided good detail in the case.

I am not the only one with this issue and it would be great if y'all gave some indication that someone is looking at this issue (and yes I realize it is not the same as this thread, burt you at least responded to a user developer)

**Comment by ShivikaK** [comment] 2021-06-23 20:19
Hello @jhullparkseed 

Thank you for reaching out and for opening the support case for your issue. 

Your support case has been received by us and is currently being reviewed and investigated.

Please continue monitoring the support case for next steps and further updates. 

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by saleweaver** [comment] 2021-06-25 07:41
> Hello @jhullparkseed
> 
> Thank you for reaching out and for opening the support case for your issue.
> 
> Your support case has been received by us and is currently being reviewed and investigated.
> 
> Please continue monitoring the support case for next steps and further updates.
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support

Hi Shivika,

I'm the author of https://github.com/saleweaver/python-amazon-sp-api. I had the error too, it seemed to me that the error occurs when multiple services are requesting access tokens from different instances at a high pace.

Can you check if the user agent for many of the requests starts with `python-sp-api`? I since have implemented key sharing using secrets manager, which stopped the error for me - but may not be ideal for every use case. 

Thanks!

**Closed** 2022-06-10 18:47 UTC
Labels: bug, Documentation, closed for inactivity
