### ISSUE TITLE
The [listFinancialEventGroups] interface unable to get all fields

### ISSUE THREAD

**Issue by always404** [amzn/selling-partner-api-docs#3295] opened 2023-08-05 06:16 UTC
From Friday, I call the “listFinancialEventGroups” interface，but can only obtain a small part fields, Are there any other people encountering this problem? I still repeat this result many times, this affects our normal work. response as follows: 
![image](https://github.com/amzn/selling-partner-api-docs/assets/62318419/ea8d5a34-9253-4116-bb61-b06d698d381e)

**Comment by zhihui** [comment] 2023-08-05 08:05
I ran into the same problem

**Comment by always404** [comment] 2023-08-05 09:27
Maybe the same problem has occurred before  https://github.com/amzn/selling-partner-api-docs/issues/1878

**Comment by ElyeM** [comment] 2023-08-09 21:26
We are having the same issue since Friday, I opened a case 13513288271

@rugved1991

**Comment by always404** [comment] 2023-08-10 13:02
@chrisskhoury Hi. The problem has continued for a week, when can it be solved? which is very serious for us. Be sure to solve it as soon as possible, thanks

**Comment by shlomieconnect** [comment] 2023-08-10 13:44
this has been a problem for us as well. from what I can gather its affecting only the Europe region.

**Comment by always404** [comment] 2023-08-11 01:04
> 

Since last Friday, only Europ region have been affected, but from yesterday, North American stations are also experiencing the same problem

**Comment by ElyeM** [comment] 2023-08-11 15:12
Right, we see that issue now on NA as well.

**Comment by rugved1991** [comment] 2023-08-13 20:45
Hi @always404,

Thanks for surfacing this issue. The Finance API team is aware and are investigating the issue. We will post an update as soon as we hear from the internal teams. 

Best,
Rugved
Solutions Architect, SP-API

**Comment by kobeleehom** [comment] 2023-08-15 03:15
I ran into the same problem

**Comment by rugved1991** [comment] 2023-08-16 15:59
Hi,

Thank you for your patience while we worked through this issue. This morning, the internal team deployed a fix for this issue. Can you please test again and check if the issue is resolved? 
I will close this thread for now. But, if you are still seeing the same issue, feel free to reopen this issue.

Best,
Rugved
Solutions Architect, SP-API

**Closed by rugved1991** 2023-08-16 15:59 UTC

**Comment by dmette** [comment] 2023-08-16 18:25
@rugved1991 we are still encountering some issues where closed financial groups are not including original total, converted total and other details about funds being transferred for the eu region.

**Comment by rugved1991** [comment] 2023-08-16 19:14
Hi @dmette,

Thanks for the update. Can you please share requestId, timestamp for the requests that are running into these issues? We can investigate further and inform the team if this is still related to the same issue.

Best,
Rugved
Solutions Architect, SP-API

**Comment by dmette** [comment] 2023-08-17 12:59
Hi @rugved1991 

Here are two instances where the details are lacking for this financial group "FinancialEventGroupId": "4vMXYrYZj0xPP-14nfpGHrMNTU4-4rBQ1CIJYr05ggs." Some responses did have the original and converted totals but the following did not:

Wed, 16 Aug 2023 18:23:27 GMT
c5364d1a-8874-4751-a3ae-87448db5000c


Thu, 17 Aug 2023 12:55:49 GMT
93df505f-c831-40c4-9dcd-2ccd4f33ef48

Thank you!
David

**Comment by dmette** [comment] 2023-08-17 14:51
@rugved1991 we also just encountered missing data on financial group _39ritw2oA3N_tlTUe6mHoSi5LIn2tN0QSDo-Eb3b7E for request bd57d268-3a09-4f82-a0fc-c0445e4cee1d at Thu, 17 Aug 2023 14:49:52 GMT.

**Comment by rugved1991** [comment] 2023-08-19 03:17
Thank you for providing the details. The internal team investigated the issue and have provided the following guidance:
"If developers are experiencing this issue, they can mitigate it by requesting data for a smaller time period which will have higher chances of success."

Best,
Rugved
Solutions Architect, SP-API

**Comment by dmette** [comment] 2023-08-21 14:56
Thanks for the feedback, @rugved1991. Have a great day!

**Comment by sally-a2x** [comment] 2023-08-24 14:26
@rugved1991 Hi! I see this issue is closed but I'm still running into this exact issue where the OriginalTotals and ConvertedTotals are missing. I've also opened up a case 13555725711 about it

RequestId: 68ace4ef-d994-47b5-a2b7-2c8147913db7
Timestamp: 2023-08-15T19:51:00.697Z
