### ISSUE TITLE
[BUG] [SP-API] `compressionAlgorithm` field is set in response but report document is actually not compressed

### ISSUE THREAD

**Issue by wolendranh** [amzn/selling-partner-api-docs#3200] opened 2023-06-21 14:29 UTC
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

According to [SP API documentation](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-retrieve-a-report#step-2-download-the-report) if `compressionAlgorithm` is set, document content should be compressed and decompressed by client. 

## Current Behavior

Currently `compressionAlgorithm` is set to `GZIP`, but report content is not compressed. 

## Context/Screenshots

This issue happens not for all requested reports but only for some. I do not see exact pattern in how it happens. 

It is confirmed to affect following reports (and maybe more):
`GET_VENDOR_INVENTORY_REPORT `
`GET_VENDOR_SALES_REPORT`
`GET_COUPON_PERFORMANCE_REPORT `

**Comment by alixleger** [comment] 2023-06-21 14:38
same problem here

**Comment by twistedFantasy** [comment] 2023-06-21 14:43
We also start facing the same issue today.

**Comment by danielYaakov** [comment] 2023-06-21 14:48
Same issue here!!

**Comment by BroncoMark** [comment] 2023-06-21 16:18
Same issue here!

Its happening for me in the following report:

GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL

**Comment by bobertlo** [comment] 2023-06-21 20:36
Also seeing this on `GET_MERCHANT_LISTINGS_ALL_DATA`

**Comment by repriceit** [comment] 2023-06-21 22:46
Ditto, this issue cropped up today, and we're getting many failures stating, "Not in GZIP format".  Clients are complaining.

**Comment by ssuhre** [comment] 2023-06-22 06:33
Further report types seem to be affected:
- GET_LEDGER_SUMMARY_VIEW_DATA
- GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL

**Comment by Daniell-Green** [comment] 2023-06-22 06:44
Same issue here with `GET_MERCHANT_LISTINGS_ALL_DATA`

**Comment by m-urminsky** [comment] 2023-06-22 08:08
Same issue with GET_SALES_AND_TRAFFIC_REPORT.

**Comment by yuvii** [comment] 2023-06-22 08:11
Same issues with these
_GET_MERCHANT_LISTINGS_INACTIVE_DATA_
_GET_FLAT_FILE_OPEN_LISTINGS_DATA_

**Comment by chocobn69** [comment] 2023-06-22 09:45
We have the same issue on various reports here ..

**Comment by ashish-atidiv** [comment] 2023-06-22 10:32
Hi Everyone
In addition to `GET_VENDOR_SALES_REPORT`, I am getting the same issue with below reports as well-
- `GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT`
- `GET_VENDOR_TRAFFIC_REPORT`

**Comment by nkdanta1** [comment] 2023-06-22 11:19
Hi everyone, we are also facing the same issue with `GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL` report.

**Comment by ginesr** [comment] 2023-06-22 13:57
Same, started yesterday in the afternoon, report type `GET_FLAT_FILE_OPEN_LISTINGS_DATA`

**Comment by kennycontreras** [comment] 2023-06-22 14:23
Same here. I'm facing an error with the following reports
`GET_SALES_AND_TRAFFIC_REPORT`
`GET_SELLER_FEEDBACK_DATA`
`GET_V1_SELLER_PERFORMANCE_REPORT`
`GET_V2_SELLER_PERFORMANCE_REPORT`
`GET_PROMOTION_PERFORMANCE_REPORT`
`GET_COUPON_PERFORMANCE_REPORT`
`GET_XML_BROWSE_TREE_DATA`

**Comment by jlevers** [comment] 2023-06-22 17:49
I'm getting many people complaining of the same issue in my client library ([jlevers/selling-partner-api](https://github.com/jlevers/selling-partner-api)), for instance https://github.com/jlevers/selling-partner-api/issues/559.

**Comment by naveenpatnana** [comment] 2023-06-22 19:31
facing the same issue for NA marketplace ### GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL report.

**Comment by puppsupr** [comment] 2023-06-22 22:51
Hi All,

The issue has been fixed. Please let us know if you still see the issue.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by m-urminsky** [comment] 2023-06-22 23:55
Hello, this still doesnt appear to be working in the eu-west-1 region.
us-east-1 seems to be working now.

**Comment by BroncoMark** [comment] 2023-06-23 00:17
Working for me now. It looks like they removed the compressionAlgorithm header for the reports that arent compressed.

**Comment by nkdanta1** [comment] 2023-06-23 04:27
Hi @puppsupr
I am still facing the issue with `GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL` report. (marketplace_code: IN)

**Comment by kelerensheng** [comment] 2023-06-23 05:38
@puppsupr 
Hello, The issue continues in the EU, including report types like below:
- GET_SALES_AND_TRAFFIC_REPORT
- GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL
- GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL
- GET_LEDGER_SUMMARY_VIEW_DATA
- GET_LEDGER_DETAIL_VIEW_DATA

**Comment by alesconti** [comment] 2023-06-23 06:09
Hi, The issue continues in the EU

**Comment by tmechsner** [comment] 2023-06-23 06:13
We are also still facing this error in EU for the following report types:

- GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL
- GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL
- GET_LEDGER_SUMMARY_VIEW_DATA

And for the following report type in US:
- GET_LEDGER_SUMMARY_VIEW_DATA

**Comment by kaipaysen** [comment] 2023-06-23 08:07
We're seeing this issue as well for EU: GET_FBA_INVENTORY_PLANNING_DATA.

**Comment by getvicky83** [comment] 2023-06-23 10:24
Issue still remains in eu

**Comment by littleylv** [comment] 2023-06-23 10:35
> 

The issue still exists...

**Comment by Daniell-Green** [comment] 2023-06-23 10:43
As a quick and dirty fix I have edited reports.py as follows:

`            if 'compressionAlgorithm' in res.payload:
                try:
                    document = zlib.decompress(bytearray(document), 15 + 32)
                except zlib.error:
                    pass`

**Comment by jacobshirley** [comment] 2023-06-23 10:46
Same issue here with EU reports

**Comment by BroncoMark** [comment] 2023-06-23 15:10
This issue is still present this morning with EU reports for me

**Comment by hinavinayak** [comment] 2023-06-23 16:52
Hello, 

Reports that reached a `DONE` processingStatus between 2`0-Jun-2023 21:59:05 UTC and 22-Jun-2023 23:36:56 UTC `may have the "Content-Encoding: gzip" header set. This can cause issues with existing implementations that use HTTP libraries that automatically decompress in the presence of this header if the implementation then tries to decompress again based on the existence of the compressionAlgorithm = GZIP field in the 2021-06-30 reports API.

You can request reports to be re-generated (calling createReport) with new output documents which will not have that header; 

Alternatively, disabling this automatic decompression in the HTTP library will allow clients to download reports regardless of whether the "Content-Encoding: gzip" header is present. This can be achieved in the Sample Code from https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-retrieve-a-report by adding the following line to the Request object.

`.header("Accept-Encoding", "")`

Full example
```

// Modified DownloadExample.java
// This example is for use with the Selling Partner API for Reports, Version: 2021-06-30
// and the Selling Partner API for Feeds, Version: 2021-06-30
import java.io.BufferedReader;
import java.io.Closeable;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.util.zip.GZIPInputStream;

import com.squareup.okhttp.MediaType;
import com.squareup.okhttp.OkHttpClient;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.Response;
import com.squareup.okhttp.ResponseBody;

/**
 * Example that downloads a document.
 */
public class DownloadExample {

  public static void main(String args[]) {
    String url = "<URL from the getFeedDocument/getReportDocument response>";
    String compressionAlgorithm = "<compressionAlgorithm from the getFeedDocument/getReportDocument response>";

    DownloadExample obj = new DownloadExample();
    try {
      obj.download(url, compressionAlgorithm);
    } catch (IOException e) {
      //Handle exception here.
    } catch (IllegalArgumentException e) {
      //Handle exception here.
    }
  }

  /**
   * Download and optionally decompress the document retrieved from the given url.
   *
   * @param url                  the url pointing to a document
   * @param compressionAlgorithm the compressionAlgorithm used for the document
   * @throws IOException              when there is an error reading the response
   * @throws IllegalArgumentException when the charset is missing
   */
  public void download(String url, String compressionAlgorithm) throws IOException, IllegalArgumentException {
    OkHttpClient httpclient = new OkHttpClient();
    Request request = new Request.Builder()
      .url(url)
      .get()
      .header("Accept-Encoding", "") // Disables transparent decompression in the OkHttp library.
      .build();

    Response response = httpclient.newCall(request).execute();
    if (!response.isSuccessful()) {
      System.out.println(
        String.format("Call to download content was unsuccessful with response code: %d and message: %s",
          response.code(), response.message()));
      return;
    }

    try (ResponseBody responseBody = response.body()) {
      MediaType mediaType = MediaType.parse(response.header("Content-Type"));
      Charset charset = mediaType.charset();
      if (charset == null) {
        throw new IllegalArgumentException(String.format(
          "Could not parse character set from '%s'", mediaType.toString()));
      }

      Closeable closeThis = null;
      try {
        InputStream inputStream = responseBody.byteStream();
        closeThis = inputStream;

        if ("GZIP".equals(compressionAlgorithm)) {
          inputStream = new GZIPInputStream(inputStream);
          closeThis = inputStream;
        }

        // This example assumes that the download content has a charset in the content-type header, e.g.
        // text/plain; charset=UTF-8
        if ("text".equals(mediaType.type()) && "plain".equals(mediaType.subtype())) {
          InputStreamReader inputStreamReader = new InputStreamReader(inputStream, charset);
          closeThis = inputStreamReader;

          BufferedReader reader = new BufferedReader(inputStreamReader);
          closeThis = reader;

          String line;
          do {
            line = reader.readLine();
            // Process line by line.
          } while (line != null);
        } else {
          //Handle content with binary data/other media types here.
        }
      } finally {
        if (closeThis != null) {
          closeThis.close();
        }
      }
    }
  }
}



```

**Comment by puppsupr** [comment] 2023-06-23 22:15
Reports that reached a DONE processingStatus between 20-Jun-2023 21:59:05 UTC and 23-Jun-202 18:55:56 UTC may have the "Content-Encoding: gzip" header set. This can cause issues with existing implementations that use HTTP libraries that automatically decompress in the presence of this header if the implementation then tries to decompress again based on the existence of the compressionAlgorithm = GZIP field in the 2021-06-30 reports API.

Reports that reached a DONE processingStatus before or after this event will continue to work with your existing implementations. It may be possible to use createReport to create a new report in place of an affected report. Downloading the new report will work with existing implementations.

Alternatively, disabling this automatic decompression in the HTTP library will allow clients to download reports regardless of whether the "Content-Encoding: gzip" header is present. This can be achieved in the Sample Code from https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-retrieve-a-report by adding the following line to the Request object.

.header("Accept-Encoding", "")
Full example

// DownloadExample.java
// This example is for use with the Selling Partner API for Reports, Version: 2021-06-30
// and the Selling Partner API for Feeds, Version: 2021-06-30
import java.io.BufferedReader;
import java.io.Closeable;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.util.zip.GZIPInputStream;

import com.squareup.okhttp.MediaType;
import com.squareup.okhttp.OkHttpClient;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.Response;
import com.squareup.okhttp.ResponseBody;

/**
 * Example that downloads a document.
 */
public class DownloadExample {

  public static void main(String args[]) {
    String url = "<URL from the getFeedDocument/getReportDocument response>";
    String compressionAlgorithm = "<compressionAlgorithm from the getFeedDocument/getReportDocument response>";

    DownloadExample obj = new DownloadExample();
    try {
      obj.download(url, compressionAlgorithm);
    } catch (IOException e) {
      //Handle exception here.
    } catch (IllegalArgumentException e) {
      //Handle exception here.
    }
  }

  /**
   * Download and optionally decompress the document retrieved from the given url.
   *
   * @param url                  the url pointing to a document
   * @param compressionAlgorithm the compressionAlgorithm used for the document
   * @throws IOException              when there is an error reading the response
   * @throws IllegalArgumentException when the charset is missing
   */
  public void download(String url, String compressionAlgorithm) throws IOException, IllegalArgumentException {
    OkHttpClient httpclient = new OkHttpClient();
    Request request = new Request.Builder()
      .url(url)
      .get()
      .header("Accept-Encoding", "") // ADD THIS LINE
      .build();

    Response response = httpclient.newCall(request).execute();
    if (!response.isSuccessful()) {
      System.out.println(
        String.format("Call to download content was unsuccessful with response code: %d and message: %s",
          response.code(), response.message()));
      return;
    }

    try (ResponseBody responseBody = response.body()) {
      MediaType mediaType = MediaType.parse(response.header("Content-Type"));
      Charset charset = mediaType.charset();
      if (charset == null) {
        throw new IllegalArgumentException(String.format(
          "Could not parse character set from '%s'", mediaType.toString()));
      }

      Closeable closeThis = null;
      try {
        InputStream inputStream = responseBody.byteStream();
        closeThis = inputStream;

        if ("GZIP".equals(compressionAlgorithm)) {
          inputStream = new GZIPInputStream(inputStream);
          closeThis = inputStream;
        }

        // This example assumes that the download content has a charset in the content-type header, e.g.
        // text/plain; charset=UTF-8
        if ("text".equals(mediaType.type()) && "plain".equals(mediaType.subtype())) {
          InputStreamReader inputStreamReader = new InputStreamReader(inputStream, charset);
          closeThis = inputStreamReader;

          BufferedReader reader = new BufferedReader(inputStreamReader);
          closeThis = reader;

          String line;
          do {
            line = reader.readLine();
            // Process line by line.
          } while (line != null);
        } else {
          //Handle content with binary data/other media types here.
        }
      } finally {
        if (closeThis != null) {
          closeThis.close();
        }
      }
    }
  }
}

**Comment by nkdanta1** [comment] 2023-06-24 08:14
thanks @puppsupr.
Confirming that issue is fixed now.

**Comment by nkdanta1** [comment] 2023-06-24 08:15
> puppsupr
Confirming that issue is fixed now.

**Comment by BroncoMark** [comment] 2023-06-24 15:02
Can also confirm that newly request reports are working

**Comment by twistedFantasy** [comment] 2023-06-26 13:51
The issue is fixed for us as well

**Closed** 2023-06-27 12:01 UTC
Labels: bug
