### ISSUE TITLE
Upload Feed Data does not work

### ISSUE THREAD

**Issue by CebulMaciej** [amzn/selling-partner-api-docs#447] opened 2021-02-26 13:07 UTC
Hello,

I have problem with upload feed data. Could anybody give me a working example data? XML/JSON something working, because i always get response that input was invalid with empty details. 

Please, help !

**Comment by johnkw** [comment] 2021-03-01 03:19
This is a duplicate of bug #389 and bug #363 - it should be closed in favor of adding to those two.

**Comment by CebulMaciej** [comment] 2021-03-01 07:08
In my case, upload data is always FATAL. Encryption works fine

**Comment by bk757** [comment] 2021-03-01 12:04
> In my case, upload data is always FATAL. Encryption works fine

@CebulMaciej me too, had you got a solution?我也是, 解决了吗？

**Comment by CebulMaciej** [comment] 2021-03-01 14:29
No, i have no solution for this case. I'm still waiting, maybie somebody will send us any example file

**Comment by bk757** [comment] 2021-03-02 02:34
@CebulMaciej upload xml dose not work,  when i change file type (.txt) all is right .  this page for more information: https://sellercentral.amazon.com/gp/help/external/G641?language=zh-CN  
Step1: download Shipping template(Flat.File.ShippingConfirm.ca.xls)  And Perfect your shipping information.
Step2: Save a other file as .txt file
Step3: Encrypt and upload the this txt file

**Comment by CebulMaciej** [comment] 2021-03-02 07:31
@bk757 could you send me example file?

**Comment by bk757** [comment] 2021-03-02 07:36
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amzn/selling-partner-api-docs"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 下午3:31
收件人:&nbsp;"amzn/selling-partner-api-docs"<selling-partner-api-docs@noreply.github.com&gt;;
抄送:&nbsp;"健伟"<768771104@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [amzn/selling-partner-api-docs] Upload Feed Data does not work (#447)





 
@bk757 could you send me example file?

**Comment by CebulMaciej** [comment] 2021-03-02 07:40
excuse me? :D

**Comment by bk757** [comment] 2021-03-02 10:33
> @bk757 could you send me example file?
`order-id	order-item-id	quantity	ship-date	carrier-code	carrier-name	tracking-number	ship-method	transparency_code	ship_from_address_name	ship_from_address_line1	ship_from_address_line2	ship_from_address_line3	ship_from_address_city	ship_from_address_county	ship_from_address_state_or_region	ship_from_address_postalcode	ship_from_address_countrycode	
408-918590-08304	116426754387	1	2021-03-01	Yun Express		YT210612126xx10	Standard											
`

**Comment by johnkw** [comment] 2021-03-02 17:34
Still looks like this is a duplicate of bug #389 and bug #363 - it should be closed in favor of adding to those two.

**Comment by bk757** [comment] 2021-03-03 06:14
@CebulMaciej `"order-id\torder-item-id\tquantity\tship-date\tcarrier-code\tcarrier-name\ttracking-number\tship-method\ttransparency_code\tship_from_address_name\tship_from_address_line1\tship_from_address_line2\tship_from_address_line3\tship_from_address_city\tship_from_address_county\tship_from_address_state_or_region\tship_from_address_postalcode\tship_from_address_countrycode\t\r\n408-918590-08304\t116426754387\t1\t2021-03-01\tYun Express\t\tYT210612126xx10\tStandard\t\t\t\t\t\t\t\t\t\t\t\r\n"`

**Closed** 2022-06-10 18:42 UTC
Labels: closed for inactivity
