### ISSUE TITLE
Amazon SP API Fba Outbound call nextToken returns the last page

### ISSUE THREAD

**Issue by kashyapsandeep** [amzn/selling-partner-api-docs#2664] opened 2022-10-24 07:51 UTC
Amazon SP API FBA Outbound issue returns the last page when we use the nextToken parameter instead of the next page

https://developer-docs.amazon.com/sp-api/docs/fulfillment-outbound-api-v2020-07-01-reference#listallfulfillmentorders

https://sellingpartnerapi-na.amazon.com/fba/outbound/2020-07-01/fulfillmentOrders?NextToken=PlaceHolderForNextToken

There are definitely more orders but we are not able to retrieve it correctly using the next token

**Comment by sungolivia** [comment] 2022-10-26 17:26
closing this as it's a duplicate of https://github.com/amzn/selling-partner-api-docs/discussions/2678

**Closed by sungolivia** 2022-10-26 17:26 UTC

**Comment by Nightterror** [comment] 2023-04-27 01:33
Did this ever get solved? The discussion doesn't seem to have an answer either. I have the same issue, consuming the next token using this endpoint returns the same page of orders, but generates a new next token. If I consume this new next token, it continues to return the same page of orders

**Comment by kashyapsandeep** [comment] 2023-04-30 07:33
Yes, Amazon did patch it up after escalating the issue through the support channels.
Just ensure that you only use the nextToken as a parameter from the second call onwards.
Note: nextToken is case sensitive

**Comment by jrrosel** [comment] 2024-02-28 16:26
I am still encountering this issue. Is there anything specific to fixing it? I am using this node package:
https://www.npmjs.com/package/amazon-sp-api

**Comment by kashyapsandeep** [comment] 2024-04-14 13:47
The issue was resolved.
Amazon pushed changes where the pagination started working correctly. 
The parameters are case-sensitive. So ensure that they match what is there in the documentation.
