### ISSUE TITLE
How can I get the image URL of product?

### ISSUE THREAD

**Issue by mcisys** [amzn/selling-partner-api-docs#1281] opened 2021-08-20 06:09 UTC
I am using GetReport API of Amazon MWS with the report type "_GET_MERCHANT_LISTINGS_ALL_DATA_", Actually it's not returning images URL? Is there a way to get image URL?

**Comment by johnkw** [comment] 2021-08-21 15:47
This is a duplicate of bug #1166 - please close.

**Closed** 2022-06-10 18:54 UTC
Labels: Documentation, enhancement request, closed for inactivity
