### ISSUE TITLE
Access to the requested resource is denied , "Unauthorized"

### ISSUE THREAD

**Issue by ankurmorabia201** [amzn/selling-partner-api-docs#261] opened 2021-01-04 13:10 UTC
Response code:
403
Response header:
{'Date': 'Wed, 30 Dec 2020 16:34:52 GMT', 'Content-Type': 'application/json', 'Content-Length': '141', 'Connection': 'keep-alive', 'x-amzn-RequestId': '252b173d-0120-4747-b400-18bc541bfeaf', 'x-amzn-ErrorType': 'AccessDeniedException', 'x-amz-apigw-id': 'YX_W6FQsIAMFoOg='}
Response content:
b'{\n  "errors": [\n    {\n      "message": "Access to requested resource is denied.",\n     "code": "Unauthorized",\n     "details": ""\n    }\n  ]\n}'

For python version, We are using botocore and boto3 libraries for signing AWS Request.

**Comment by johnkw** [comment] 2021-01-18 03:16
This seems to be a duplicate of bug #38, which is still open with no resolution.

**Comment by johnkw** [comment] 2021-01-18 03:22
Bug #280 is also a duplicate of this one. In that bug they say again to open a support ticket, so perhaps the current status of bug #38 is no one at Amazon knows what it means... at least not without some sort of painful additional server-side investigation?

**Closed** 2022-06-10 18:39 UTC
Labels: closed for inactivity
