### ISSUE TITLE
Blank screen is displayed when user visits the app link for authorization

### ISSUE THREAD

**Issue by shahviren1985** [amzn/selling-partner-api-docs#1935] opened 2022-01-19 16:51 UTC
I have logged seller central ticket - ID - 7588294922

Previously the same app link was allowing sellers to authorize the app. But when sellers are using this link, they are seeing blank white screen.

Thanks

**Comment by AntanasMisiunas** [comment] 2022-01-19 17:04
Having the same issue. Yesterday everything was fine. By inspecting the console, it is clear there's an uncaught error being thrown and hence blank page.

**Comment by DexterSnyder** [comment] 2022-01-19 17:11
We are having the same issue here.

**Comment by jimmy-ross-xapix** [comment] 2022-01-19 17:12
same here, it was also mentioned in this issue from the past which has taken up traction today: https://github.com/amzn/selling-partner-api-docs/issues/1543

**Comment by sPaCeMoNk3yIam** [comment] 2022-01-19 17:12
Same issue here, **HIGH SEVERITY**.

Also, this might be connected.
https://github.com/amzn/selling-partner-api-docs/issues/1543

**Comment by justin-coberly** [comment] 2022-01-19 17:18
Same issue here, this needs to be fixed asap.

**Comment by openbridge-james** [comment] 2022-01-19 17:55
Same here...

**Comment by tspicer** [comment] 2022-01-19 18:30
same issue

**Comment by Sai-Srikar** [comment] 2022-01-19 18:31
We are also facing the same issue

**Comment by lesyriad** [comment] 2022-01-19 18:40
Sad that this is an issue but glad Im not the only one experiencing this.  Please fix ASAP as this is a major issue and during our official app launch week as well :(

**Comment by parvathm** [comment] 2022-01-19 19:02
Hi,

Thank you for notifying us. We are looking into this issue and will update the fix as soon as possible.

Thanks,
Parvathm
SP API Developer Support.

**Comment by ShivikaK** [comment] 2022-01-19 20:20
Hello,

The issue has been fixed and it should be working as expected. Can you please confirm on your end as well?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by openbridge-james** [comment] 2022-01-19 20:31
Working from what I can see, thanks for the quick turn around.

**Comment by jimmy-ross-xapix** [comment] 2022-01-19 20:32
Yep, working here too :)

**Comment by ShivikaK** [comment] 2022-01-20 19:23
Hello,

Thank you for confirming. As the issue is fixed, I am closing this issue. If error persists or a new issue occurs, please open a support case with us.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Closed by ShivikaK** 2022-01-20 19:23 UTC
Labels: bug, documentation
