### ISSUE TITLE
Questions about /fba/inbound/v0/shipments/{shipmentId}/labels

### ISSUE THREAD

**Issue by Kevin-qs** [amzn/selling-partner-api-docs#319] opened 2021-01-20 06:12 UTC
Why do I call this interface, the returned URL, the downloaded PDF file is blank?

**Comment by johnkw** [comment] 2021-02-03 21:33
Sounds like a duplicate of bug #329 - this bug came first, but there's a lot more information in 329.

**Closed** 2022-06-10 18:40 UTC
Labels: Documentation, enhancement request, closed for inactivity
