### ISSUE TITLE
[BUG] [SP-API] [Issue] Missing shipment-item-id in GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING report

### ISSUE THREAD

**Issue by stayhero** [amzn/selling-partner-api-docs#3027] opened 2023-03-25 19:23 UTC
## I'm submitting a...

<pre><code>[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

We used to receive the column `shipment-item-id` in the above report. 

## Current Behavior

The column `shipment-item-id` is empty for most orders (at least for orders on the Amazon.de german marketplace).  The column was not removed but it is just empty. 

## Context/Screenshots

We need the values of the column to distinguish (i.e. previously imported) order items from new ones. 

A sample report ID is 685193019440.  

## Your Environment

We simply use the SP API for reports to create and retrieve the  GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING reports. 

We  are observing this behavior for reports since Friday, March 24, 2023.

**Comment by hinavinayak** [comment] 2023-03-27 21:14
We are looking into this with the Report Authoring Team.

**Comment by rosalie-Janssen** [comment] 2023-03-29 11:53
This is also happening on the _GET_AMAZON_FULFILLED_SHIPMENTS_DATA_.  Originally is was only for Europe but now happening for the US as well.

**Comment by rachelleborowicki** [comment] 2023-03-29 21:27
We are experiencing the same on GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL, this is causing some serious issues for our system.

**Comment by compumatic** [comment] 2023-03-31 14:33
this same issue exists when downloading the Amazon Fulfilled Shipments report manually from Amazon Fulfillment Reports in Seller Central

**Comment by BCampanile** [comment] 2023-03-31 17:05
rachelleborowicki and compumatic:  have either of you been able to resolve this problem or find a work around?

**Comment by compumatic** [comment] 2023-03-31 17:35
unfortunately no resolution here yet...  I only noticed it yesterday and thought I had a problem with my database or import script for the file.  last night I realized the Shipment Item Id data was missing (column exists but no values) and this seems to have started a few days ago.  I thought I was crazy until I found this bug report.  I sent a message to Amazon seller support last night and they completely misunderstood the issue and gave a non-responsive answer, so I sent a clarifying response this morning.

as noted in the original submission "We need the values of the column to distinguish (i.e. previously imported) order items from new ones." this is obviously a critical field as I see no other way of uniquely identifying records and avoiding either missing parts of an order (where fba splits into more than one shipment) or duplicating order entries.  I'm assuming this is a bug that will be fixed and applied retroactively to reports and not a feature change?  does anyone have a creative workaround if Amazon does not correct this?

**Comment by BCampanile** [comment] 2023-03-31 17:39
Compumatic  I agree precisely.  We have opened a ticket with very similar wording.   I spent the entire day yesterday looking for a solution or work around.  It is particularly bad timing with today being month end.    Any thoughts/ideas/solutions would be appreciated.

**Comment by compumatic** [comment] 2023-03-31 18:42
Amazon support just responded with:
apologies yadda yadda yadda...
In this case the specialized team has let us know that this issue has been recognized as a widespread issue, they are currently working hard to get this solved ASAP.
apologies yadda yadda yadda...

good news is they acknowledge the issue, bad news is no resolution or timeline provided.

**Comment by compumatic** [comment] 2023-04-02 01:23
it looks like this field is starting to populate again on new reports today, still waiting and hoping they will go back and fix prior report dates...

**Comment by call-me-ghosty** [comment] 2023-04-05 15:24
We fixed this for several customers of ours, by just creating an md5-hash out of order-id and order-item-id and writing it into the shipment-item-id field. So we are getting an unique identifier like the one Amazon used to populate before.

**Comment by BCampanile** [comment] 2023-04-05 15:34
call-me-ghostly:  If Amazon adds back the shipment-item-id to the orders missing the data, your md-5 hash won't match theirs will it?  Won't duplication issues?

**Comment by call-me-ghosty** [comment] 2023-04-05 15:36
> call-me-ghostly: If Amazon adds back the shipment-item-id to the orders missing the data, your md-5 hash won't match theirs will it? Won't duplication issues?

We are overwriting whatever is given in the field, by that we are just using our identifier for further logic

**Comment by compumatic** [comment] 2023-04-05 17:40
I thought the issue is that more than one record can have the same order-id and order-item-id, so if you made a hash out of those values wouldn't that hash be the same for both records?

**Comment by call-me-ghosty** [comment] 2023-04-05 18:36
> I thought the issue is that more than one record can have the same order-id and order-item-id, so if you made a hash out of those values wouldn't that hash be the same for both records?

We did‘nt met this issue by now, but thanks for the hint.

**Comment by rosalie-Janssen** [comment] 2023-04-11 11:50
I know Amazon started populating the reports again , but has anyone heard anything about the older data.  Looks like anything from 3/23 until the fix day is still not populated.

**Comment by compumatic** [comment] 2023-04-12 19:49
I gave up on waiting.  I imported the records that were missing this field data to a temporary table and created my own unique record values for this field, then I processed them and moved on...

**Comment by JsonSong89** [comment] 2023-04-14 07:13
> > I thought the issue is that more than one record can have the same order-id and order-item-id, so if you made a hash out of those values wouldn't that hash be the same for both records?
> 
> We did‘nt met this issue by now, but thanks for the hint.

you can't do that ,sometimes 
the  one order item  quantity_shipped is 2 
but the shipment has two item with 1 quantity ,so the order-id  order-item-id  are same

**Comment by yogeshbablu89** [comment] 2023-04-21 21:40
Issues seems to be fixed as of 04/14 .

**Comment by johnkw** [comment] 2023-04-25 13:59
Yes this does seem to be fixed.

FYI, while this bug was happening, we just ignored the records completely if they had a blank shipment-item-id.  During the bug it seemed after some period the field was correctly being restored, so the net result was just our reports were being delayed by a few days.

**Closed** 2023-10-27 00:18 UTC
Labels: bug, closing soon
