### ISSUE TITLE
I can't get all products on Amazon SP API. How can I do this?

### ISSUE THREAD

**Issue by FatmaSedaOZYURT** [amzn/selling-partner-api-docs#2754] opened 2022-12-01 12:47 UTC
### Discussed in https://github.com/amzn/selling-partner-api-docs/discussions/2750

<div type='discussions-op-text'>

<sup>Originally posted by **FatmaSedaOZYURT** November 29, 2022</sup>
Hi everybody,
I can't get all products. I searched but I didn't understand this flow.
I read this [page ](https://developer-docs.amazon.com/sp-api-blog/docs/manage-your-product-listings-lifecycle-with-selling-partner-api). Unfortunatelly, I couldn't do it.
Where is that I overlook?
I'm waiting for your answer.
Thanks in advance.</div>

**Comment by arorasahil1209** [comment] 2022-12-01 17:53
Even i was not able to find the endpoint and operations which needs to be use here :(

**Comment by sungolivia** [comment] 2022-12-01 21:07
closing due to duplicate of https://github.com/amzn/selling-partner-api-docs/discussions/2750

**Closed by sungolivia** 2022-12-01 21:07 UTC
