### ISSUE TITLE
message: Access to requested resource is denied, code: Unauthorized

### ISSUE THREAD

**Issue by od081274gil** [amzn/selling-partner-api-docs#2896] opened 2023-02-01 08:14 UTC
### Discussed in https://github.com/amzn/selling-partner-api-docs/discussions/2894

<div type='discussions-op-text'>

<sup>Originally posted by **od081274gil** January 31, 2023</sup>
Hi 
I have problem, who can halp me ?
We have a published application with users, for some users sometimes we get the error "Access to requested resource is denied" for all api query"
Example 
Date: Tue, 31 Jan 2023 15:13:26 GMT
Content-Type: application/json
Content-Length: 141
Connection: keep-alive
x-amzn-RequestId: a915abe5-33e0-4bd5-a6e9-45ae0033bedd
x-amzn-ErrorType: AccessDeniedException

  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}</div>

**Comment by sungolivia** [comment] 2023-02-01 18:50
Closing this issue as it's a duplicate of https://github.com/amzn/selling-partner-api-docs/discussions/2894

**Closed by sungolivia** 2023-02-01 18:50 UTC
