### ISSUE TITLE
FinanceApi BUG : listFinancialEvents : InvalidInput

### ISSUE THREAD

**Issue by yan15195755798** [amzn/selling-partner-api-docs#3285] opened 2023-07-29 16:20 UTC
The same error is returned on calling "listFinancialEvents" with [nextToken] parameter.
It seems that the error is caused since yesterday and happen irregularly. Sometimes the error is returned on the first [nextToken] , sometimes the error is returned on the 2nd/3rd/4th... [nextToken], and sometimes all the [nextToken] are requested successfully.

I change [MaxResultsPerPage] to "10" and try again, but the error is still caused. Is it a bug of selling-partner-api？

"errors": [
{
"code": "InvalidInput",
"message": "$errorResponse.Message",
"details": ""
}
]
}

**Comment by emildoa** [comment] 2023-07-31 03:15
Just commenting that I'm having exactly the same issue.

**Comment by jimmy-ross-xapix** [comment] 2023-07-31 07:40
we are having the same issue still

**Comment by JohnMirro** [comment] 2023-07-31 09:34
We are too

**Comment by jimmy-ross-xapix** [comment] 2023-07-31 09:55
also created this one earlier: https://github.com/amzn/selling-partner-api-docs/issues/3283

**Comment by naveenpatnana** [comment] 2023-07-31 14:16
Even we are facing the same issue.

**Comment by titansoftime** [comment] 2023-07-31 19:20
Same.

**Comment by cyrieu** [comment] 2023-08-01 01:30
same issue

**Comment by bchecketts** [comment] 2023-08-01 01:31
Same issue. retrying multiple times eventually gets it to work

**Comment by lizdeika** [comment] 2023-08-01 11:39
same issue, even tried posted before/after 15minutes and MaxResults 1, nothing helps

**Comment by mid** [comment] 2023-08-01 11:41
Same issue.

**Comment by rt3722** [comment] 2023-08-01 14:52
Facing exact same issue.

**Comment by omrishaked** [comment] 2023-08-01 20:07
This is a duplicate of https://github.com/amzn/selling-partner-api-docs/issues/3283

**Comment by titansoftime** [comment] 2023-08-01 20:31
> This is a duplicate of #3283

The slight difference is that this ticket is for listFinancialEvents and #3283 is for listFinancialEventsByGroupId.

**Comment by lizdeika** [comment] 2023-08-02 07:16
duplicate or not, it's 5 days already and it's still down

**Comment by emildoa** [comment] 2023-08-03 17:11
@chrisskhoury Thanks for letting us know.

By the way, I went to the URL you shared and it seems like you're only flagging the ListFinancialEventsByGroupId endpoint as yellow, but the ListFinancialEvents is also behaving the same.

**Comment by chrisskhoury** [comment] 2023-10-24 09:29
resolving as issue seems to be resolved, feel free to reopen if issue persists

**Closed by chrisskhoury** 2023-10-24 09:29 UTC
Labels: bug
