### ISSUE TITLE
Reports API requiring report types param, should be optional

### ISSUE THREAD

**Issue by amanz360** [amzn/selling-partner-api-docs#61] opened 2020-10-22 14:55 UTC
Hello, just as the title says, I'm not able to make a request to filter available reports without sending in the reportTypes parameter. The documentation for the reports API says that it should be optional but when I attempt to omit it from my request, I get the following error response:

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "One or more required parameters missing",
      "details": "reportTypes;"
    }
  ]
}

This is a big problem for me because we've built around pulling the _GET_DATE_RANGE_FINANCIAL_TRANSACTION_DATA_ report, which is not able to be requested via API but once generated in seller central, had been available to download via the API. If I try to filter by that report type specifically, then I get an "Access to this resource is forbidden." error. I assume that once I can omit the reportTypes parameter or specify that report type, then I should be able to pull that report again the same way I had already been doing.

Help on this would be much appreciated!

**Comment by amanz360** [comment] 2020-10-22 15:06
For reference, this is the endpoint in question: https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md#getreports

**Comment by ykw090721** [comment] 2020-12-17 07:36
@amanz360  Have you solved this problem? How to solve it

**Comment by amanz360** [comment] 2020-12-30 21:30
Hello again, just wanted to give people an update here. So I haven't tested if you can omit the report types parameter yet, but filtering by the `GET_DATE_RANGE_FINANCIAL_TRANSACTION_DATA` report type is working again as of a few days ago.

That resolves the core problem of my issue, though not sure if this should remain open until someone confirms the report types param is optional or confirms it should never be optional.

**Comment by rogersv** [comment] 2020-12-30 21:40
@amanz360 The documentation says
`Either reportTypes or nextToken is required.`
See the documentation that you linked above.

**Comment by amanz360** [comment] 2020-12-30 22:28
I'm aware that the documentation says that, but this behavior is divergent from reports via MWS and seems like an unnecessary limitation. So I'll leave it up to someone on Amazon's team to decide if this issue is closed or not since the main issue for me was being unable to either omit the filter or filter by this specific report type. Since the latter path is now available, the former doesn't matter as much to me, but I still think it should be available.

**Comment by rogersv** [comment] 2020-12-30 22:47
@amanz360  You started an issue where you said the documentation is incorrect. Now you say that you know that the documentation is correct but you want it to work differently. Sounds like a change request. 
I am going to stop commenting in this repo and as you requested and let amazon answer future questions.

**Comment by johnkw** [comment] 2021-02-02 18:26
`reportTypes` definitely should be optional.  Right now not only is it required, but it's capped at 10 items (even though the `pageSize` is allowed to be up to 100).  Alternatively, the field could be left required but a special value such as `all` could be used for the normal behavior from MWS, of not filtering based on report type.

Right now this is a big regression from MWS.

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md#getreports

**Comment by johnkw** [comment] 2021-07-14 20:00
This continues to be an annoying regression from MWS. Also the documentation on https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md#getreports is still not matched to the SP-API. The `reportTypes` is still listed as optional, but if you don't include it the error is:
```
"code": "InvalidInput",
"message": "One or more required parameters missing",
"details": "reportTypes;"
```

**Comment by rugved1991** [comment] 2022-01-28 22:52
Hi @johnkw, 

The "reportTypes" attribute is marked as optional in the API schema definition because if you are using the pagination option, reportTypes is not required during that request.
So if you have 1000 reports, you would make a call to first 100 with "reportTypes" parameter and then in the response you would receive a nextToken. In the following request to getReports, you do not need to send in any other parameter apart from "nextToken".
If it was marked as required parameter in the schema, we would have to submit this parameter in the pagination as well.
I hope this helps. Please reopen if you have any additional questions.

Best,
Rugved
Solutions Architect, SP API

**Closed by rugved1991** 2022-01-28 22:52 UTC
Labels: Researching

**Comment by johnkw** [comment] 2022-01-29 04:11
I understand that it's currently optional in only the trivial sense that it's not required during pagination.

However, I agree with the original poster that it should be made fully optional. This is a big regression from MWS, where there was no such requirement. If you're requesting reports both through the API and the web for example it's not to be able to see them all without needing to less every conceivable `reportType`.

Also (and may this deserves a separate bug) it's strange that you can't get a list of `reportId` entries. The normal way of using the API is to request a dozen reports and then sit there calling `getReports` until they all finish, but it should would make more sense to only get the exact actual ones you requested. It would surely be more resource-efficient on Amazon's side as well.
