### ISSUE TITLE
[BUG] Failure to use Restricted Data Token

### ISSUE THREAD

**Issue by tahir1122** [amzn/selling-partner-api-docs#2011] opened 2022-02-03 18:36 UTC
**Describe the bug**
I am able to retrieve RDT for getOrders API but using the RDT as 'x-amz-access-token' results in 403 unauthorized

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#step-1-get-an-rdt-getorders

**Issue Details**
I am successful in retrieving RDT for getOrders API endpoint using the following POST request:

POST https://sellingpartnerapi-na.amazon.com/tokens/2021-03-01/restrictedDataToken

{
  "restrictedResources":
    {
      "method": "GET",
      "path": "/orders/v0/orders",
      "dataElements": ["buyerInfo", "shippingAddress"]
    }
}

The response contains the 'restrictedDataToken'. When I try to use this RDT for GetOrders API endpoint by replacing 'x-amz-access-token' with the RDT  (as mentioned in the documentation), it fails with the following error:

403 Forbidden

{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

**I am able to retrieve Orders when using the Access token but it fails when using RDT**

Any help would be appreciated

**Comment by kpconnell** [comment] 2022-02-03 23:12
are you signing it with the RDT in place?

**Comment by NeftaliAcosta** [comment] 2022-02-11 18:48
I have the same problem, the documentation is not clear on how to generate an RDT. What headers go or what additional parameters do I have to send?

**Comment by KanishkVashisht** [comment] 2022-02-18 06:31
I'm facing the same issue. Can someone on the amazon team look into this?

**Comment by foxfiring** [comment] 2022-02-22 10:27
应该是APP没有PII权限

**Comment by daniel031699** [comment] 2022-02-23 05:02
@tahir1122  I also encountered the same problem. Has it been solved? Ask for help

**Comment by tahir1122** [comment] 2022-03-14 14:49
This issue is still not resolved. Can anyone please help?

**Comment by Valkozaur** [comment] 2022-04-01 09:25
I have a similar problem, if somebody resolved it please let me know. Amazon If you read this, please give us accurate documentation on when we should add the access token, before the signing or after the signing.
And also should we take in place the access token granted from the with the ClientSecret.

**Comment by RobertMartin-nz** [comment] 2022-05-04 23:23
I have the exact same issue.  My seller application tries calls getOrdes with an LWA token and I don't get all the shipping details.  My app is registered for 'Direct-to-Consumer Delivery'.  Searching the docs it seems I need to get an RDT (Restricted data token) and pass this as the 'x-amz-access-token' instead of the normal LWA token.

I can call and get an RDT passing the exact settings from the example docs 

{
  "restrictedResources": [
    {
      "method": "GET",
      "path": "/orders/v0/orders",
      "dataElements": ["buyerInfo", "shippingAddress"]
    }
  ]
}

but when I use it (by assigning it to x-amz-access-token and signing my messageas normal I get the 403 'Access to requested resource is denied.' error.

Does anyone have this working?

**Comment by GreaText** [comment] 2022-05-23 14:26
I have the exact same problem listed here. I can get orders with LWA token that does not include restricted data. I can retrieve a restricted data token, but when I use the RDT to get orders I'm returned a 403 unauthorized error.

**Comment by RobertMartin-nz** [comment] 2022-05-23 20:51
Ok for everyone still struggling with this, I have found and fixed the issue I had with this.

The issue is that if you send invalid JSON in your request to get an RDT instead of returning an error, Amazon returns ok with a token that has no access to anything.  When you use this token to call an API you then get an 'Access to requested resource is denied.' message.  Which is true, because you don't have access  but also horribly misleading.  I was running around checking my Dev account, refreshing my permissions etc.

Anyway the JSON I was using actually not exactly as shown in the manual, I was passing restrictedResources as a JSON object but should have been a array.

**Comment by GreaText** [comment] 2022-05-23 23:25
I had coded as you.. sending an object for restrictedResources and not an array. I changed the code to send an array, now I'm getting a different error, but I think this might be the solution to get past this particular problem.

**Comment by RobertMartin-nz** [comment] 2022-05-23 23:48
Glad to hear it might have helped.  

Just in case it helps others, there is the exact (working) JSON I am sending.  This is for access to orders.
This is the JSON body I pass through (UTF8 encoded)

{
  "restrictedResources": [
    {
      "method": "GET",
      "path": "/orders/v0/orders",
      "dataElements": [
        "buyerInfo",
        "shippingAddress"
      ]
    }
  ]
}

**Comment by GreaText** [comment] 2022-05-24 14:07
Here is the same code in PHP

```
['restrictedResources'][] = [
    'method'        => 'GET',
    'path'          => '/orders/v0/orders',
    'dataElements'  => [ 'buyerInfo', 'shippingAddress' ],
]
```

**Comment by MachuskoJ** [comment] 2022-06-01 17:12
Thank you Robert! I was having a similar issue and the json formatting was the culprit.

**Comment by gesenlik** [comment] 2023-03-02 15:17
Hi, have you been able to find a definitive solution for this? I am trying to solve the same error. The json is correct but does not accept the rdt token.

**Comment by Valkozaur** [comment] 2023-03-02 16:29
Hello, for me I did not have enough rights.
Therefore I was getting this error message.

**Comment by gesenlik** [comment] 2023-03-02 22:36
thanks for your answer...

**Comment by DanyPell** [comment] 2023-05-16 17:47
Same as OP. Can get RDT but can't get the orders when using the RDT. Where is Amazon?

**Comment by StormTech07** [comment] 2023-06-28 09:13
Same ! using python : 
tokens_api = Tokens(credentials=credentials)
response = tokens_api.create_restricted_data_token(
    restrictedResources=[
        {
            "method": "GET",
            "path": "/orders/v0/orders",
            "dataElements": ["buyerInfo", "shippingAddress"]
        }
    ]
)

return : 
sp_api.base.exceptions.SellingApiForbiddenException: [{'code': 'Unauthorized', 'message': 'Access to requested resource is denied.', 'details': ''}]

**Comment by darrelbott** [comment] 2023-09-14 03:03
Python and Postman don't work.  I get the RDT token, but it doesn't work on the path that I am calling.  I get a 403 error that reads the token no longer valid, malfunctioned, etc.

I'm passing the RDT token in the header instead of the access token.  Not getting this 403 error 

I plan on getting in touch with Amazon tomorrow, but why would a token they just gave me not work on the very thing it gave me a token for?  And they are getting rid of MWS lol.

**Closed** 2024-03-17 00:21 UTC
Labels: bug, Documentation, closing soon
