### ISSUE TITLE
[BUG] [SP-API] [Issue] List Financial Event Groups  no total when processing status closed. 

### ISSUE THREAD

**Issue by mbolder** [amzn/selling-partner-api-docs#3306] opened 2023-08-12 14:37 UTC
## I'm submitting a...

[x] Bug report  

## SP-API Name and Version or Report/Feed Type
Latest version

## Expected Behavior
Show the total amount of all financial events, like when the status is open under "OriginalTotal". 

## Current Behavior
{'FinancialEventGroupId': 'xxxxx', 'ProcessingStatus': 'Closed', 'BeginningBalance': {'CurrencyCode': 'EUR', 'CurrencyAmount': 0.0}, 'FinancialEventGroupStart': '2023-08-04T13:06:48Z', 'FinancialEventGroupEnd': '2023-08-11T12:08:42Z'}

## Your Environment
We load all financial events and create our in-house bookings, based on the total we can compare our results.

**Comment by omrishaked** [comment] 2023-08-14 08:31
Same here

**Comment by shlomieconnect** [comment] 2023-08-14 18:36
It's missing other data as well. This is a duplicate of #3295

**Closed** 2023-08-18 07:26 UTC
Labels: bug
