### ISSUE TITLE
Rate Limit clarification

### ISSUE THREAD

**Issue by TFL-LeadDev** [amzn/selling-partner-api-docs#426] opened 2021-02-21 20:43 UTC
Hi,

I've been testing some calls for the **/catalog/v0/items**. I've been trying to find the right rate for my application to make calls and while testing I noticed that I could sometimes do 10 requests in about 2 seconds, sometimes it takes more time but on all cases I'm getting only 200 response codes.

This is great but I'm also confused since according to the documentation this specific endpoint has a rate limit of 1 request per second and I know there are **Dynamic usage plans** but according to the [documentation](https://github.com/amzn/selling-partner-api-docs/blob/1e8bae98a61d69166a0706c67cfb978e5192a705/guides/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md#usage-plans) the good practice should be to read the **x-amzn-RateLimit-Limit** header and adjust the calling rate based on that value, the issue is that I noticed that in all cases I keep getting 1.0 as my rate limit value but clearly I can make requests faster than that (I'd say probably 3-8 requests per second). 

Some days ago I was making calls at a rate of about 2 calls per second and I was getting consistent 429s.

I feel like my rate limit increased but it's not reflected in **x-amzn-RateLimit-Limit**.

Is there something I'm misunderstanding about rate-limits and dynamic usage plans?.

Thanks for looking into this issue.

**Comment by callumb123** [comment] 2021-02-22 07:37
I have a similar issue ( #323 ) which has been closed as I have been told they are looking into it. It's been a couple weeks and I haven't had any update though so please don't close this issue as hopefully seeing it is causing issues for

**Comment by ShivikaK** [comment] 2021-02-22 21:11
Hello @TFL-LeadDev 

Thank you for raising this issue.

As @callumb123 mentioned, we do have an issue reported regarding rate limits for /catalog/v0/items which is being investigated by our engineering team. I will add a note regarding your questions as well to get better clarification about the rate limits.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by cgaugel** [comment] 2021-08-13 12:25
The problem is also at your /createFeed and /createFeedDocument API endpoint. The API is still full of bugs after month now.

**Closed** 2022-06-10 18:42 UTC
Labels: Documentation, enhancement request, closed for inactivity
