### ISSUE TITLE
Getting FBA inbound shipment availability with SP-API

### ISSUE THREAD

**Issue by spchuang** [amzn/selling-partner-api-docs#1732] opened 2021-11-29 19:20 UTC
I have been digging through the SP-API documentation to find out if there's data that shows when the incoming FBA inventory will be available for selling.

I am currently using report type `GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL` to get all the POs with SKU and quantity, but I couldn't find where to see when those incoming inventory are estimated to be available for selling.

**Comment by stefnats** [comment] 2021-11-29 22:20
Take a look at Report Types `GET_FBA_MYI_ALL_INVENTORY_DATA` or `GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA` - They should contain the data you are looking for.

**Comment by spchuang** [comment] 2021-11-30 23:18
@stefnats  do those 2 reports show inbound shipment data (to FBA warehouses)?

**Comment by stefnats** [comment] 2021-12-08 10:54
Hey @spchuang can you confirm that `afn-inbound-receiving-quantity` is the metric you are looking for ?

**Comment by stefnats** [comment] 2021-12-08 10:55
Oh i see, you might want to know *when* the item / FNSKU is arriving? For that, i don't know that. I thought you meant that you need to inbound receiving/shipped quantity and not the actual date.

**Comment by johnkw** [comment] 2022-04-17 16:44
This is a duplicate of bug #357. Please close in favor of the original.

**Closed** 2022-11-19 00:25 UTC
Labels: closing soon
