### ISSUE TITLE
[BUG] [SP-API] [Finance API - 400 Errors for listFinancialEventsByGroupId]

### ISSUE THREAD

**Issue by jimmy-ross-xapix** [amzn/selling-partner-api-docs#3283] opened 2023-07-28 13:33 UTC
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
SP API Finance API - istFinancialEventsByGroupId operation

## Expected Behavior
When using listFinancialEventsByGroupId, the SP API endpoint should respond with the financial events for that group ID

![Screenshot 2023-07-28 at 15 15 21](https://github.com/amzn/selling-partner-api-docs/assets/62943550/a82107f0-fd7e-4b20-8f11-34e11f31d4ac)

## Current Behavior
Since Thursday, we have seen a huge increase in unexpected 400 Errors and keep seeing them today across different seller accounts

Are others seeing this too?

**Comment by joeybab3** [comment] 2023-07-28 15:46
Can confirm we are seeing this as well with the same response, started randomly

**Comment by always404** [comment] 2023-07-29 07:44
I confirmed that we have also had the same problem, and randomly appeared, which brought us huge trouble

**Comment by etimmons** [comment] 2023-07-29 10:55
confirmed here as well

**Comment by yan15195755798** [comment] 2023-07-29 16:09
I confirm that we also have the same problem and it appears randomly, which has caused us great trouble and I have not found a solution

**Comment by LukaszBalazy** [comment] 2023-07-29 22:17
@yan15195755798 what worked for me is adding really aggressive retry policy. Since it'a appearing randomly you can either retry requests multiple times one after another when you get 422.

**Comment by yan15195755798** [comment] 2023-07-31 02:53
> @yan15195755798 what worked for me is adding really aggressive retry policy. Since it'a appearing randomly you can either retry requests multiple times one after another when you get 422.

I tried it, but it still didn't work

**Comment by emildoa** [comment] 2023-07-31 03:17
I'm having this same issue but in the listFinancialEvents endpoint.

**Comment by emildoa** [comment] 2023-07-31 03:22
> @yan15195755798 what worked for me is adding really aggressive retry policy. Since it'a appearing randomly you can either retry requests multiple times one after another when you get 422.

That worked for me on Thursday, I was retrying like for 2 hours until I got a successful run, but since Friday I haven't been able to solve the issue.

It started randomly, but now it's not random.

**Comment by titansoftime** [comment] 2023-07-31 15:24
Same exact same problem. Started a few days ago.

**Comment by rugved1991** [comment] 2023-07-31 17:00
Hi,

Thank you for surfacing this issue. The internal teams are actively working on this issue.
I will provide an update when there is a workaround or when the issue is resolved.
Thank you for your patience and cooperation.

Best,
Rugved
Solutions Architect, SP API

**Comment by Paul-J-Barrett** [comment] 2023-08-01 03:33
This has us dead in the water. We need a fix for this ASAP.

**Comment by naveenpatnana** [comment] 2023-08-01 12:11
We are also facing the same issues, it is stopping us from generating the reports and were not able to take subsequent decisions.

**Comment by estebanangel** [comment] 2023-08-01 22:26
Same response on my end, we depend on this data for a lot of business processes.

**Comment by marvs** [comment] 2023-08-02 05:20
We are having the same problem as well when requesting the listFinancialEvents endpoint with a nextToken.

I tried escaping the token, as well as setting the MaxResultsPerPage to 25 (from 100), but the error still persists.

**Comment by mjng93** [comment] 2023-08-02 15:26
Same issue with us. Pretty urgent endpoint needed for us to make business decisions. @rugved1991 is there any way we can follow progress on this bug? Is this the best place?

**Comment by guyil** [comment] 2023-08-03 01:24
Same issue here, and I notice it keeps returning the same nextToken. Please fix it ASAP.

**Comment by titansoftime** [comment] 2023-08-03 02:38
> Same issue here, and I notice it keeps returning the same nextToken. Please fix it ASAP.

I thought the same thing, however at least in my case upon further inspection the tokens has a mere 16 or so character difference hidden in there.

**Comment by fitihuang** [comment] 2023-08-03 02:58
https://github.com/amzn/selling-partner-api-docs/discussions/3281
before amazon resolve this question,
i took this suggested from [houyachao](https://github.com/houyachao),
although this is not a so correct solution for it, but it work.

**Comment by bchecketts** [comment] 2023-08-03 03:10
Same error here for several days now. We sleep 10s after a failure and retry up to 6 times after a failed response and it almost always works by the 6th retry.  Probably 50% or more of requests are failing on the first attempt.

If you are experiencing this, make sure to submit a case using the link on https://developer.amazonservices.com/support so that this gets the real attention to the right team.  Posting here on Github seems to be seen as "random people on the internet are complaining" and probably not seen by the right team. But when you open a case it gets routed the the right team, and is tied to an actual account with the ability for them to investigate specifically.

**Comment by chrisskhoury** [comment] 2023-08-03 16:01
> Same issue with us. Pretty urgent endpoint needed for us to make business decisions. @rugved1991 is there any way we can follow progress on this bug? Is this the best place?

Hello,

You can monitor the status of the issue in this [Selling Partner API - Health Dashboard](https://sellercentral.amazon.com/sp-api-status).

Thank you!

Chris
Solution Architect, SP API

**Comment by mjng93** [comment] 2023-08-03 17:22
> 

Thanks a lot @chrisskhoury @rugved1991 ! This is helpful. FWIW, we are seeing the exact same issue on the ListFinancialEvents  endpoint, as @emildoa in the thread mentioned. That doesn't seem to be showing as having an issue in the Health Dashboard.

**Comment by estebanangel** [comment] 2023-08-09 15:08
hi, any progress here? almost 2 weeks and this endpoint is still failing. This is one of the most important endpoints in all the API, incredible that there's no solution yet :(

**Comment by titansoftime** [comment] 2023-08-10 21:11
Looks fixed now! At least for listFinancialEvent pull.

**Comment by chrisskhoury** [comment] 2023-10-24 09:32
resolving as error is fixed, feel free to reopen if issue persists

**Closed by chrisskhoury** 2023-10-24 09:32 UTC
Labels: bug

**Comment by devsohsarai** [comment] 2023-11-12 01:59
I am also facing the same issue with getorders NextToken:  {
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Invalid Input",
            "details": ""
        }
    ]
}
