### ISSUE TITLE
GET_SELLER_FEEDBACK_DATA got CANCELLED after 5 minutes status IN_PROGRESS

### ISSUE THREAD

**Issue by rohitdobariya** [amzn/selling-partner-api-docs#1101] opened 2021-07-20 04:52 UTC
**Describe the bug**
GET_SELLER_FEEDBACK_DATA got CANCELLED after 5 minutes status IN_PROGRESS also There are feedback also in account

**Additional context**
from FBA account other report able to request and download but GET_SELLER_FEEDBACK_DATA  request and try to get the reportDocumentId if Processing status DONE but always Processing status IN_PROGRESS(5 minutes) to  CANCELLED not sure why CANCELLED, Marketplace Id is A1F83G8C2ARO7P

**Comment by johnkw** [comment] 2021-07-21 16:57
This sounds like a duplicate of bug #920 perhaps?  If so, please close this one in favor of the original.

**Comment by rohitdobariya** [comment] 2021-07-21 17:27
@johnkw This is not duplicate of bug actually we do have feedback in the account but based on the doc there are are two possibility  CANCELLED status one is manually cancelled or no data found. In my case I am only one working on this so there are no chance to canceled and secondly we have feedback already. still not getting report and got cancelled .

**Comment by johnkw** [comment] 2021-07-23 02:47
Might have no rows due to filtering or something. I still suspect it's a duplicate of bug #920 but you should contact Seller Central Support.

**Comment by abuzuhri** [comment] 2021-12-31 10:03
I notes that when i request report for time less than 5 days i get CANCELLED status and the same if i fill enddate  , I should only fill startdate . 

there is no documentation for this problem in amazon https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#performance-reports  but i notes that after testing many times

**Comment by stefnats** [comment] 2022-01-01 22:00
Seems like this is behavior for when no data is available (in the selected time range). Can you confirm that?

**Comment by abuzuhri** [comment] 2022-01-01 22:03
Yes this true after check my account I have only one feedback for last 5
days .

Maybe this the response

**Comment by johnkw** [comment] 2022-01-01 22:12
If so, that's a duplicate of bug #920 and you should really move the comment to that bug.  The OP on this bug claimed this is not the same as bug #920.

**Closed** 2022-11-20 00:26 UTC
Labels: bug, Documentation, closing soon
