### ISSUE TITLE
Is there an issue with raising SP-API support cases ?

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#2631] opened 2022-10-10 14:07 UTC
I m getting the following message when attempting to raise a SP-API case through the SC support page

The service is currently unavailable. Please try again later.

And also, all of my previous SP-API cases are no longer showing int the case log

Is there an issue ?

Thanks

**Comment by sungolivia** [comment] 2022-10-10 17:13
I was able to access the SC support page and was able to raise a case. Anyone else experiencing this?

**Comment by cmlkx** [comment] 2022-10-10 18:44
@nrogers805  - maybe dumb question, but are you 100% you signed into the correct seller central account to view your cases (maybe you have a store account and a separate developer account) ?

**Comment by Adrian-T-AMZN** [comment] 2022-10-10 20:17
Hello everyone,

Thank you for your patience and understanding.

The root cause for the issue has been identified and the fix has been deployed. Please verify that the error has been resolved and confirm the same for us.

If further assistance is required, please provide us the Merchant Token for your accounts.

Please note this fix is only for the issue with raising SP-API support cases.

Thanks,
Adrian T.
Selling Partner API Developer Support

**Comment by Adrian-T-AMZN** [comment] 2022-10-11 20:59
Hello everyone,

We haven't seen any more occurrences of this issue within the last day. 

If further assistance is required, please provide us the Merchant Token for your accounts along with the exact parameter or the HAR file and console dump file that can be used to debug.

Please note this fix is only for the issue with raising SP-API support cases.

Thanks,
Adrian T.
Selling Partner API Developer Support

**Comment by sungolivia** [comment] 2022-10-14 18:41
Closing this for now, please reopen if you have issues feel free to reopen!

**Closed by sungolivia** 2022-10-14 18:41 UTC
Labels: bug, Question, Researching
