### ISSUE TITLE
Unclear How To Obtain Brand Analytics Selling Partner API Role

### ISSUE THREAD

**Issue by tspicer** [amzn/selling-partner-api-docs#1989] opened 2022-01-28 22:56 UTC
The "Brand Analytics Selling Partner API role" is required to make requests for various reports. However, unlike most other roles, this is not a role we can select for our application. There is no Brand Analytics check box. The documentation is vague on this point as well. 

Can someone provide some details on how we can attach this role so customers can get access to these reports? Thanks.

**Comment by moltar** [comment] 2022-01-30 12:43
It turns out, which isn’t documented anywhere, you need to register and create a completely separate application in the Vendor Central account. And you can only authorize your own VC account.

**Comment by tspicer** [comment] 2022-01-31 13:40
@moltar , thanks for that context. I sent a note to support and they simply told me to "select the role checkbox".

**Comment by Guerri114** [comment] 2022-01-31 16:37
There's two things you should check in Vendor Central:

1. Make sure your Developer Profile has _Brand Analytics_ role checked in the **Data Access** section: https://vendorcentral.amazon.com/developer/register
2. After you've confirmed your Developer Profile has the role, then go into your individual application clients (click: **Edit App)** and ensure the _Brand Analytics_ role is attached as needed. See list of clients here: https://vendorcentral.amazon.com/sellingpartner/developerconsole
3. If you make changes to an application client, be sure to self-authorize and generate a new refresh token. To do this, go to the Developer Consoler, click the dropdown arrow next to **Edit App**, and then click **Authorize**.

**Comment by rugved1991** [comment] 2022-02-02 21:08
Hi @tspicer,

The Brand Analytics role is currently in closed beta for Public Developers. The role is openly available to Sellers, Vendors, and Brands (Private Developers) that wish to access the data for their own use. We expect to also open the role to Public Developers by end of this quarter. Please watch for future announcements.

Rugved
Solutions Architect, SP API

**Closed** 2022-02-11 16:52 UTC
Labels: wontfix

**Comment by jlevers** [comment] 2022-02-23 01:48
@rugved1991 could you give us any sense when the Brand Analytics role will be made available for public developers?

**Comment by amz-tools** [comment] 2022-03-25 11:32
Hi @rugved1991,

according to the [new announcement](https://developer-docs.amazon.com/sp-api/page/release-notes#reports-api) from 23rd March the Brand Analytics Role should now be available to all developers:

> This report requires the Brand Analytics Selling Partner API role which is now available to all sellers.

However, we just checked Developer Central and it seems its still not available. Do you have any update on that?

**Comment by tspicer** [comment] 2022-03-25 13:01
@amz-tools , it should be present in the developer, not the app, profile. This caused me some initial confusion since roles are in both places.

**Comment by amz-tools** [comment] 2022-03-25 13:52
Thanks for helping out @tspicer, found it.

**Comment by moltar** [comment] 2022-03-26 06:04
So can someone confirm if this will work with the Vendor Central reports, or is this only for Seller Central?

**Comment by timmyscj** [comment] 2022-04-12 01:06
> It turns out, which isn’t documented anywhere, you need to register and create a completely separate application in the Vendor Central account. And you can only authorize your own VC account.

I haven't had any luck getting the new reports mentioned in the March release announcement working for Vendor Central Reports. The previous reports work fine.

**Comment by sarasdeveloper** [comment] 2022-04-24 01:41
Anyone had any luck as a 3rd party developer access seller central business reports? Our apps has been approved for "Brand Analytics" role, yet we are getting authorisation errors when we are trying to call SC Business Reports Api

**Comment by orpeleg8** [comment] 2022-05-23 12:05
I've check the box "Brand Analytic" in my developer profile seller central, but getting unauthorized  - "Access to the resource is forbidden". Anyone had any luck yet?

**Comment by RMagician** [comment] 2022-06-23 07:25
We've just received the Brand Analytics developer role, now applied for the app level brand analytics role (yes there are two roles!). 

So if you're getting unauthorized access after getting the developer level role, don't forget to then request the app-level role.

**Comment by KR2025** [comment] 2022-06-25 09:40
We have the same issue of "access to the resource is forbidden", while we have brand analytics role activated at:
1. Developer profile (found here: https://sellercentral.amazon.co.uk/developer/register)
2. App profile (found here: https://sellercentral.amazon.co.uk/sellingpartner/developerconsole/application?appId=XXX - your appid will be here) - found in menu at partner networks > develop apps)

You need to do these in sequence. While this fixed some reports, brand analytics continues to not be available. Would appreciate any additional feedback.

Question: is there a difference between SP API only and SP API and MWS? We have SP API setup for app only - but perhaps you should do both.

**Comment by vipul-neon** [comment] 2022-10-06 05:01
Hi,

It is very unclear on why Amazon is rejecting Brand Analytics API access to us. We have applied via public developer profile and also submitted app for listing

**Comment by sreejithlillydoo2** [comment] 2022-12-01 12:41
Hi All,
 
I would need to access the brand analytics api and pull the data to redshift table. The first step of creating the access token has done, now I am facing challenge to find the exact API end point to send a GET request to access the brand analytics data. Is somebody already aware about the URL then please help me on this, or anything other steps is required before send the GET request, I believe a GET request directly to the end point with the bearer access token can pull the json data. Please correct me and help if my understanding is wrong.

Thanks.

**Comment by RMagician** [comment] 2023-02-06 09:53
We just lost access to these reports, had been using them without issue.
```
SellingApiForbiddenException: [{'code': 'Unauthorized', 'message': 'Access to the resource is forbidden', 'details': ''}]
```

If anyone if suffering the same and finds a solution please share !

**Comment by sreejithlillydoo2** [comment] 2023-02-06 10:24
I also want to know the issue, to which end point you are making the request.

**Comment by AppDev2020-admin** [comment] 2023-02-17 22:30
> We've just received the Brand Analytics developer role, now applied for the app level brand analytics role (yes there are two roles!).
> 
> So if you're getting unauthorized access after getting the developer level role, don't forget to then request the app-level role.

@RMagician What did you do to get access to the Brand Analytics Role? We have been requesting for more than 2 weeks now and keep getting rejected. The latest rejection message was: 'Your update should include a website URL that provides details about the services your application offers to Amazon Sellers. The website should display information about function details, and other features of your app. ' We tried adding bits and pieces of information on our website but they are never satisfied. Any tips for us?

**Comment by AppDev2020-admin** [comment] 2023-02-23 21:43
> Anyone had any luck as a 3rd party developer access seller central business reports? Our apps has been approved for "Brand Analytics" role, yet we are getting authorisation errors when we are trying to call SC Business Reports Api

Hi @saras-daton . Can you share your process to get 'Brand Analytics Role' access?

**Comment by Blochergroup** [comment] 2023-11-30 14:45
Is there any update on this?

I have enabled the Role in the Developer Profile as well as the App profile but can't retrive
GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT

I get following Error:
  

> "errors": [
>     {
>       "code": "Unauthorized",
>       "message": "Access to the resource is forbidden",
>       "details": ""
>     }
>   ]

**Comment by sreejithlillydoo2** [comment] 2023-11-30 14:52
I also have the same issue , still follow up with amazon support , they always forward me some documents link which is not unclear and have no solution .

**Comment by sreejithlillydoo2** [comment] 2023-11-30 14:58
Could anybody post a video or document which have the steps to retrieve the sp api data at least through postman tool.

**Comment by Blochergroup** [comment] 2023-11-30 15:18
@sreejithlillydoo2 got it working by taking the following steps.

1. Add the role to your developer profile
2. Add the role to your app
3. Generate a new refresh token after your app changes got approved

my request looks like this:
`
POST https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/reports {"reportType": "GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT", "reportOptions": {"reportPeriod": "WEEK"}, "dataStartTime": "2023-10-12T00:00:00.000Z", "dataEndTime": "2023-10-18T23:59:59.000Z", "marketplaceIds": ["A1PA6795UKMFR9"]}
`

**Comment by sreejithlillydoo2** [comment] 2023-11-30 16:36
@Blochergroup , Thanks for your response.
I could not query any of the end points other than generation access token with https://api.amazon.com/auth/o2/token . This I can successfully generated.
Could you may be forward the market listing url , so that I would also have a try with that.
What will happen if  we enable the below option in the App registration window
"Yes, I will delegate access to PII to another developer's application."
Thank you .

**Comment by Blochergroup** [comment] 2023-11-30 16:43
@sreejithlillydoo2 
take a look if you have set everything up right by taking a look at this video:
https://www.youtube.com/watch?v=gp5kTI8I3pU

You can use this repo to make a sample request:
https://github.com/jakobowsky/new-sp-api/

**Comment by renanhrt** [comment] 2024-03-26 16:28
I've read all this thread because I had the same problem. Here's what I got; I hope it resolves your problem:

First, set the Brand Analytics role on your developer profile.
https://sellercentral.amazon.co.uk/developer/register

After that is done, if you have already created your application, you can apply the Brand Analytics role now. To do that, simply go to the Apps Central in your Amazon Seller Central or access through this link, replacing 'XXX' with your App ID:
https://sellercentral.amazon.co.uk/sellingpartner/developerconsole/application?appId=XXX

After all that, **REMEMBER** to generate a new refresh token to apply all changes that were made.

Hope it works :)
