### ISSUE TITLE
Usage Plans and Rate Limits for response header

### ISSUE THREAD

**Issue by rxxy** [amzn/selling-partner-api-docs#225] opened 2020-12-18 12:47 UTC
I have read the documents related to rate limit. If `x-amzn-RateLimit-Limit` in the response header represents the rate, how to get the burst?
If the sudden increase can be obtained, my program can better call the api

Thanks

**Comment by nodisk8800** [comment] 2020-12-23 03:08
SPAPI are rate limited using the token bucket algorithm.
1,Call less frequently aligned with your rate limits.
2,Rely on push notifications over polling mechanisms.
3,Use batch APIs where possible.

only the Orders API use dynamic usage plans.

**Comment by johnkw** [comment] 2022-04-16 20:31
This is a duplicate of https://github.com/amzn/selling-partner-api-docs/issues/86#issuecomment-911114383

**Comment by rugved1991** [comment] 2022-05-11 05:53
Hi @rxxy,

Please reopen the issue if you have any additional questions.
You can also refer to our new blog post on [strategies to optimize rate limits for your application workloads](https://developer-docs.amazon.com/sp-api-blog/docs/strategies-to-optimize-rate-limits-for-your-application-workloads).

Best,
Rugved
Solutions Architect, SP API

**Closed by rugved1991** 2022-05-11 05:53 UTC
Labels: answer in docs
