### ISSUE TITLE
we are trying to use amazon sp-api and get the information about reports but it gave us error

### ISSUE THREAD

**Issue by nomi992** [amzn/selling-partner-api-docs#3000] opened 2023-03-10 13:02 UTC
we are trying to use amazon sp-api and get the information about reports but it gave us error "Error: [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]" we configured roles policies and users and also register application but its still give us same error.
![Untitled-3](https://user-images.githubusercontent.com/71398761/224322304-118663da-3350-4fc9-ac0b-4c53e9036eb3.jpg)
![Untitled-4](https://user-images.githubusercontent.com/71398761/224322317-84a9dc20-42b1-4a23-8cd0-acb95500fa4c.jpg)
![Untitled-5](https://user-images.githubusercontent.com/71398761/224322321-62105c25-3b5d-4873-ba86-7b8708994a6c.jpg)
![Untitled-1](https://user-images.githubusercontent.com/71398761/224322323-acaf5e98-0509-4619-961b-3341595c55cf.jpg)
![Untitled-2](https://user-images.githubusercontent.com/71398761/224322327-f71c1f25-ad13-40e9-bf95-b0b4ea7fd5c0.jpg)
![image](https://user-images.githubusercontent.com/71398761/224322549-9b80e3f5-66f1-47b2-ba80-f79168018a33.png)
![image](https://user-images.githubusercontent.com/71398761/224322572-bb009452-d8cf-45eb-bfb3-054df02eb5ab.png)

**Comment by sungolivia** [comment] 2023-03-10 18:53
closing as it's a duplicate of https://github.com/amzn/selling-partner-api-docs/discussions/2999

**Closed by sungolivia** 2023-03-10 18:53 UTC
