### ISSUE TITLE
Work with Sandbox

### ISSUE THREAD

**Issue by Andru4o** [amzn/selling-partner-api-docs#31] opened 2020-10-07 09:49 UTC
Hello.
Is there a user interface for sandboxing? To create orders, replenish the catalog and more. And then work with this through the API

**Comment by charliecode** [comment] 2020-10-09 01:02
@Andru4o  If you're referring to a UI like MWS scratchpad, I have not seen anything like that mentioned in the docs. Of course with the new SP-API a sandbox is available, however it's programmatic. In the event you weren't aware of it, it can be found [here.](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#the-selling-partner-api-sandbox)

**Comment by ShivikaK** [comment] 2020-10-09 21:25
Hello @Andru4o,

Currently we provide a static sandbox environment with mock request and response.

The details of the sandbox environment are provided in the Developer Guide section - The Selling Partner API sandbox

Do let us know if you face any issues or have any further questions.

**Comment by Andru4o** [comment] 2020-10-13 21:44
> Hello @Andru4o,
> 
> Currently we provide a static sandbox environment with mock request and response.
> 
> The details of the sandbox environment are provided in the Developer Guide section - The Selling Partner API sandbox
> 
> Do let us know if you face any issues or have any further questions.

The main problem is how to create test products, orders and etc to work with it by SP-API . And how we can create a test account to generate this data.

**Comment by seanevan** [comment] 2020-10-16 21:21
@Andru4o, our product team is aware of the need for a dynamic sandbox. I will share your feedback with them to help with prioritizing this functionality.

Best regards,
Sean Evans
Manager, Support Engineering

**Comment by ericblade** [comment] 2020-11-20 04:38
I was pretty excited when I saw in the documentation, that a sandbox was available.  And then when I got my code ready to roll, I investigated it further, and discovered that it is... not actually a sandbox at all.

**Comment by charliecode** [comment] 2020-11-20 06:27
@ericblade Any constructive thoughts? You're right, progress could 100% def be made. Would love to hear your thoughts on how that could happen. Wisdom from experts is always valuable.

**Comment by ericblade** [comment] 2020-11-21 01:19
Well, I'm hoping that @seanevan 's remark that a "dynamic sandbox" is something that is hopefully being worked on.

A true sandbox would work just like your regular service would, probably with read access to the live catalog (or a recent duplicate of it), and writes deployed to a special copy of the service that is only accessible from the sandbox.  So you can *actually* test all of your inputs, that all of the expected outputs work properly.  Not merely a "does my request format work" and "does my response handler work for the one scenario supported".

Just like I'm sure that the API deployment has at the very least a staging and a production instance, there should also be a copy of production running as a sandbox.

**Comment by mmdotz** [comment] 2022-05-20 20:42
Has there been any action on this enhancement request?

**Comment by gokigoks** [comment] 2022-08-04 14:34
Something similar to the scratchpad would definitely be nice. It would at least make comparing results from both SPAPI and MWS quicker and better.

**Comment by ramsesIII** [comment] 2022-09-30 14:00
Is there a Scratchpad for SP-API ?????

**Comment by rugved1991** [comment] 2022-11-22 08:54
Hi @ramsesIII,

We currently do not have a Scratchpad for SP API. We have accepted this as a feature request. Please subscribe to our [RSS feed](https://developer-docs.amazon.com/sp-api-blog/docs) on SP API website to receive real time updates on [Announcements](https://developer-docs.amazon.com/sp-api/changelog).

Best,
Rugved
Solutions Architect, SP API.

**Closed by rugved1991** 2022-11-22 08:54 UTC
Labels: enhancement request

**Comment by SohailChohan143** [comment] 2023-08-30 11:36
i have same problem i want test api but i dont have orders in my seller account, i want to create a sandbox envirnoment where i can create test order to test my api response

**Comment by ericblade** [comment] 2023-09-05 04:17
@rugved1991 That's great that you are finally considering it, 2 years after, and about 3 years after it should've been completed already.  But that in no way whatsoever makes this task closed.

It is absolutely ridiculous that there is not a sandbox environment -- It is impossible to test any write functionality without modifying my personal live data, or the live data of my users, and that is simply unacceptable.  It is almost literally blowing my mind that anyone is using this API for *anything* when it is in an untestable state.

**Comment by jamsahb143** [comment] 2024-01-30 11:34
Any updates on this?
