### ISSUE TITLE
[BUG] [SP-API] Listing Items API: "Ascent merchants" 400 Error Message

### ISSUE THREAD

**Issue by jimmy-ross-xapix** [amzn/selling-partner-api-docs#3712] opened 2024-04-16 12:31 UTC
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
PATCH /listings/2021-08-01/items/{sellerId}/{sku}

## Expected Behavior
- we submit 1000s of listing updates on behalf of many sellers and have so far not experienced issues when pushing updates for Title, Bullet Points, Description, Generic Keywords

## Current Behavior
- For a specific seller, we tried submitting over 100 updates today, but for the first time received this 400 Error Message: 
"The operation requested is not supported for Ascent merchants in retail marketplaces."
- Yesterday, the same seller had no such problems
- We cannot find any reference to what an "Ascent" merchant is online or in documentation. Is anyone else seeing this? Do you know what it might mean?

## Context/Screenshots
response code: 400
response body: { "errors": [ { "code": "InvalidInput", "message": "The operation requested is not supported for Ascent merchants in retail marketplaces.", "details": "" } ] }

## Your Environment
We have a public app on the marketplace used by 100s of sellers

**Comment by jimmy-ross-xapix** [comment] 2024-04-16 12:40
Also opened a case, case ID: 15122636381

**Comment by TkTech** [comment] 2024-04-16 13:25
We're encountering this now too. IMO, this looks like an attempt by Amazon to block the Ascent Repricer (https://ascentrepricer.com/) and they've been a little overzealous with a regex.

**Comment by jimmy-ross-xapix** [comment] 2024-04-16 15:16
> We're encountering this now too. IMO, this looks like an attempt by Amazon to block the Ascent Repricer (https://ascentrepricer.com/) and they've been a little overzealous with a regex.

Hmm really weird, please also open a case if you havent already so it gets a chance of being heard

**Comment by dominicplouffe** [comment] 2024-04-16 20:30
Anyone have any luck with this?  We are having the same issue for a bunch of our customers.  I have submitted an ticket with Amazon but no response yet.

**Comment by senxiaoxing** [comment] 2024-04-17 01:31
We also encountered the same problem, before this, the api was working fine.

**Comment by jimmy-ross-xapix** [comment] 2024-04-17 06:42
still seeing the issue here and got an unhelpful response to the case, writing again now to them. please open your own cases to apply pressure.

**Comment by luckTan** [comment] 2024-04-17 08:53
使用patchlistings 也返回这个The operation requested is not supported for Ascent merchants in retail marketplaces

**Comment by WendyMay** [comment] 2024-04-17 08:59
the same with feedType value: JSON_LISTINGS_FEED

**Comment by andrewgnyc** [comment] 2024-04-17 13:20
Same issue here.  Opened case 15120279701 with developer support.

**Comment by hinavinayak** [comment] 2024-04-17 22:59
Update: We have recognized a fix for this and are working through unblocking the impacted merchants.

**Comment by luckTan** [comment] 2024-04-19 01:40
Hello, may I ask if this issue has been resolved so far? I have still encountered a prompt stating that The operation requested is not supported for Ascent transactions in retail markets




诗与远方
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amzn/selling-partner-api-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月18日(星期四) 上午7:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amzn/selling-partner-api-docs] [BUG] [SP-API] Listing Items API: "Ascent merchants" 400 Error Message (Issue #3712)





 
Update: We have recognized a fix for this and are working through unblocking the impacted merchants.

**Comment by hinavinayak** [comment] 2024-04-19 02:45
> Hello, may I ask if this issue has been resolved so far? I have still encountered a prompt stating that The operation requested is not supported for Ascent transactions in retail markets 诗与远方 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "amzn/selling-partner-api-docs" ***@***.***&gt;; 发送时间:&nbsp;2024年4月18日(星期四) 上午7:00 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [amzn/selling-partner-api-docs] [BUG] [SP-API] Listing Items API: "Ascent merchants" 400 Error Message (Issue #3712) Update: We have recognized a fix for this and are working through unblocking the impacted merchants. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

We expect the issue is resolved for most merchants. If you can please open a support case on this and share a case-id here and we can check. 

Best

**Comment by invoker233** [comment] 2024-04-23 08:25
> Update: We have recognized a fix for this and are working through unblocking the impacted merchants. 

That was the error at first, now the error is  the operation requested is not supported for Multi-Channel Fulfillment enabled accounts in this marketplace

**Comment by invoker233** [comment] 2024-04-23 08:25
case-id 9734548532

**Comment by chapmanjw** [comment] 2024-04-29 16:41
@jimmy-ross-xapix The Listings Items APIs do not yet support the "fulfillment only" programs like Buy with Prime (we're working on that - stay tuned for announcements). However, there was a bug that prevented regular merchants who were also enrolled in Buy with Prime from using the Listings Items APIs. This bug should now be resolved. If you continue to experience any issues with regular merchant accounts, please open a support case so that we can troubleshoot further.

**Closed by chapmanjw** 2024-04-29 16:41 UTC
Labels: bug
