### ISSUE TITLE
[BUG] Amazon Sp Api is not allowing to add more than one destination

### ISSUE THREAD

**Issue by farid-hussain-qbatch** [amzn/selling-partner-api-docs#1850] opened 2021-12-28 06:08 UTC
**Describe the bug**
I want to add multiple destinations for different subscriptions but it is not allowing me.
It says 
"A destination with arn arn:aws:sqs:us-west-2***** already exists for the application amzn1.sp.solution *******************"
However I am using different ARN with different name.

**Screenshots**
<img width="1440" alt="Screenshot 2021-12-27 at 4 51 50 PM" src="https://user-images.githubusercontent.com/87980789/147533730-338d804f-18fa-4d5e-a4c9-28e9951f04c0.png">

In simple words it only allows me to add one destination, when ever I try to add second destination, it gives me the same error

**Comment by kpconnell** [comment] 2021-12-28 14:50
Two things - 1) once a destination exists, you cannot add it again.   That is normal.   2) You cannot create two subscriptions for the same notification type for the same app.  This is a restriction, and its not documented, but it makes sense if you think about it.  No app should really *need* the same message sent to two different places.

**Comment by farid-hussain-qbatch** [comment] 2021-12-29 05:18
I am trying to add two different destinations for two different subcription. I want to subscribe  notifications for ANY_OFFER_CHANGED and PROCESS_REPORT_FINISHED.
Kindly notice in screenshot, that I am trying to add new destinations for different notification type.

**Comment by kpconnell** [comment] 2021-12-29 13:14
> I am trying to add two different destinations for two different subcription. I want to subscribe notifications for ANY_OFFER_CHANGED and PROCESS_REPORT_FINISHED. Kindly notice in screenshot, that I am trying to add new destinations for different notification type.

Kindly read my post.  You are simply adding it again and don't realize it.

**Comment by farid-hussain-qbatch** [comment] 2021-12-30 05:05
Please help me out what am I doing wrong here.
First I created the destination for ANY_OFFER_CHANGED.

notification.create_destination(name='AnyofferChanged', arn='arn:aws:sqs:us-west-2:*************:AnyOffersChangedQueue')

After that I am trying to create destination for the PROCESS_REPORT_FINISHED, but it is not allowing me.

notification.create_destination(name='ProcessReportFinish', arn='arn:aws:sqs:us-west-2:**************:ReportProcessingFinishedQueue')

but it is not allowing me. please help me out.

**Comment by farid-hussain-qbatch** [comment] 2021-12-30 06:44
<img width="1440" alt="Screenshot 2021-12-30 at 11 44 06 AM" src="https://user-images.githubusercontent.com/87980789/147728082-c89bd00e-7633-43b3-bfde-8721f5d1a6fb.png">

See there is only one destination

**Comment by kpconnell** [comment] 2021-12-30 22:45
I can confirm this is now a bug as well.  I just got it trying to create a destination on a brand new queue.  

![image](https://user-images.githubusercontent.com/1077478/147792683-3a71b90a-e332-4dd7-96a0-b776bc142dd0.png)

**Comment by shahviren1985** [comment] 2022-01-02 15:23
I am having same issue. Unable to create new destination.

It seems you can create only one destination for one app in given region. Even if you want to create destination for different sellers it is not possible because the token you create is grantless.

**Comment by kpconnell** [comment] 2022-01-04 13:36
I do think this is a change in behavior and or a new bug...

**Comment by farid-hussain-qbatch** [comment] 2022-01-05 08:58
Thank you for updating.

**Comment by kpconnell** [comment] 2022-01-06 18:21
> I do think this is a change in behavior and or a new bug... I've opened case 9422075841 (North America)

Finally made it past the gauntlet of Level 2 support and my ticket is now with engineering.....

**Comment by kpconnell** [comment] 2022-01-07 14:50
Also interesting this is occuring on creating either event bridge or sqs...        "code": "Conflict",
      "message": "The requested resource conflict with a resource in the server.",
      "details": "A destination with arn aws.partner/sellingpartnerapi.amazon.com/xxxx/amzn1.sp.solution.xxx-xx-xx-xx-xx already exists for the application amzn1.sp.solution.xx-xx-xx-xx-xx"

**Comment by alperozhan** [comment] 2022-01-10 17:58
Experiencing the same issue for North America region while creating a new destination.

**Comment by zhouzr** [comment] 2022-01-11 08:43
I am having the same issue in fast east region.
I got an error when i create destination to receive report processing finished message.
{
  "errors": [
    {
      "code": "Conflict",
      "message": "The requested resource conflict with a resource in the server.",
      "details": "A destination with arn arn:aws:sqs:us-east-1:xxxxxxxxxxxx:xx-xxxx-report-processing-finished already exists for the application amzn1.sellerapps.app.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
    }
  ]
}
But I never use this arn in fe, and the response of getDestinations as follow
{
    "payload": [{"resource":{"sqs":{"arn":"arn:aws:sqs:us-east-1:xxxxxxxxxxxx:xx-xxxx-any-offer-changed"},"eventBridge":null},"destinationId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx","name":"ANY_OFFER_CHANGED"}]
  }

**Comment by ShivikaK** [comment] 2022-01-12 01:32
Hello,

Thank you for raising this issue.

The error has been reported to our respective engineering team and is currently being investigated. Once the root cause is identified, I will get back to you with further details and next steps to resolve the error. If you have raised a support case with us, please let me know here.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by zhouzr** [comment] 2022-01-12 03:18
We have raised a support case which ID is 9216407381 about this issue.

**Comment by iamricks** [comment] 2022-01-12 18:59
We have opened a case as well, ID: 9475980491

**Comment by shuaidd** [comment] 2022-01-13 02:25
I had the same problem

**Comment by ShivikaK** [comment] 2022-01-13 04:01
Hello everyone,

Thank you for your patience and understanding. 

The root cause for the issue has been identified and the fix has been deployed. Please verify that the error has been resolved and confirm the same for us.

Please note this fix is only for errors encountered when attempting to create multiple destinations for **SQS workflow.** 

For **Event Bridge workflow,** it is working as designed because there can only be one destination created per AWS account. For multiple destinations, you will need to use different AWS accounts. This functionality will be added in the Notifications Use Case Guide as well.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by kpconnell** [comment] 2022-01-13 11:25
Working for me now.   NOTE:  This appears to have modified the behavior of the API a bit:

1)  deleteSubscriptionById is no longer grantless* 
2) you now cannot have more than one subscription per seller account per type (conflict on createSubscription) (This makes sense..) 

* the grantfulness of notifications is going to be highly problematic unless SP-API automatically removes subscriptions  when an app gets de-authorized, which I don't think it does.  As an app developer, I want to be able to delete subscriptions (and therefore destinations) after I am de-authorized.  I will add a feature request.

**Comment by alperozhan** [comment] 2022-01-13 11:27
Thanks Shiviva

Issue is resolved for me (us-east-1)

**Comment by stefnats** [comment] 2022-01-13 21:35
@kpconnell I think it was not possible to have more than 2 subscriptions per developer per type per seller in MWS either.

**Comment by shuaidd** [comment] 2022-01-15 08:13
> I had the same problem

Issue is resolved for me

**Comment by farid-hussain-qbatch** [comment] 2022-01-17 13:42
Issue has been resolved for me too.
Thanks

**Closed** 2022-01-17 13:42 UTC
Labels: bug, documentation

**Comment by ShivikaK** [comment] 2022-01-19 20:30
> Resolved for me now.
> 
> NOTE: This appears to have modified the behavior of the API a bit:
> 
>     1. deleteSubscriptionById is no longer grantless*
> 
>     2. you now cannot have more than one subscription per seller account per type (conflict on createSubscription) (This makes sense..)
> 
> 
>     * the grantfulness of notifications is going to be highly problematic unless SP-API automatically removes subscriptions  when an app gets de-authorized, which I don't think it does.  As an app developer, I want to be able to delete subscriptions (and therefore destinations) after I am de-authorized.  I will add a feature request.

Hello @kpconnell 

We reviewed the deleteSubscriptionById operation and the behavior has not been changed which means that it should still be a grantless operation. If you are facing issues with this API operation, I would request you to open a support case with us to further investigate it.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by battmush** [comment] 2023-11-06 19:07
> @kpconnell I think it was not possible to have more than 2 subscriptions per developer per type per seller in MWS either.

This is absolutely not true: in MWS you were able to have multiple subscriptions for different destinations for single notification types.  We're in the process of migrating from MWS to SP-API and are in the situation where attempting to register a second destination for `REPORT_PROCESSING_FINISHED` notifications yields:

`{
    "errors": [
        {
            "code": "StateConflict",
            "message": "The resource specified conflicts with the current state.",
            "details": "Subscription already exist for notification type REPORT_PROCESSING_FINISHED"
        }
    ]
}` 

This is architecture-breaking for our application.

**Comment by brinto-evident** [comment] 2024-04-08 09:24
I have an amazon SQS queue for which i created destination using marketplaces US, DE and AU for `ORDER_CHANGE` notification. When I try to create another destination using the marketplace GB, I am getting this message: 

```
[{'code': 'Conflict', 'message': 'The requested resource conflict with a resource in the server.', 'details': 'A destination with arn arn:aws:sqs:eu-west-2:xxxxxxxxxxxx:order-queue already exists for the application amzn1.sp.solution.xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'}]
```

How could I possibly solve this?
