### ISSUE TITLE
/fba/inventory/v1/summaries

### ISSUE THREAD

**Issue by ahlmackie** [amzn/selling-partner-api-docs#129] opened 2020-11-20 15:01 UTC
is any one else having authorization issues with this endpoint (res status code 403)? 
I am using the sellingpartnerapi-eu.amazon.com host 
I'm passing authorization on all the other end points i have used so far, so just a bit strange

**Comment by JacksonJeans** [comment] 2020-11-23 09:29
Do your requests to other APIs works from the SP-API ?

**Comment by ahlmackie** [comment] 2020-11-23 10:10
yes, i've tried a dozen other endpoints and they all work ok..

**Comment by JacksonJeans** [comment] 2020-11-23 11:19
The HTTP status `403 `can have various reasons. You will always get a JSON back from Amazon with a more precise differentiation of the error.

In the SP-API we have several error cases that lead to the status `403 `and ultimately do not authorize you.

To identify the error more accurately, we need your canonical request. There it is usually already obvious why you get a `403 ` status back.

**Comment by ahlmackie** [comment] 2020-11-23 11:50
Here you go:

GET
/fba/inventory/v1/summaries
granularityId=A1F83G8C2ARO7P&granularityType=Marketplace&marketplaceIds=A1F83G8C2ARO7P&startDateTime=2020-01-01
host:sellingpartnerapi-eu.amazon.com
user-agent:amkapp/v1.0 (language=javascript)
x-amz-access-token:Atza|<token>
x-amz-date:20201123T114051Z

host;user-agent;x-amz-access-token;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

**Comment by JacksonJeans** [comment] 2020-11-23 12:05
Unfortunately, I have often seen that the users of the API do not specify a `content-type` in their canonical request, although this must be included in the normal header. Already tried to specify it? I also get a 403 if I do not specify a `content-type`. Below I describe a problem where I also get a 403.

I also see that your `canonical_uri` does not end with `/`. Other users had similar problems with GET requests, but it didn't help them if the URI ends with `/` or they set the content-type. But maybe this helps you?

Try this one:
```
GET
/fba/inventory/v1/summaries/
granularityId=A1F83G8C2ARO7P&granularityType=Marketplace&marketplaceIds=A1F83G8C2ARO7P&startDateTime=2020-01-01
content-type: application/json
host:sellingpartnerapi-eu.amazon.com
user-agent:amkapp/v1.0 (language=javascript)
x-amz-access-token:Atza|
x-amz-date:20201123T114051Z

content-type;host;user-agent;x-amz-access-token;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

**Comment by ahlmackie** [comment] 2020-11-23 12:13
still no luck unfortunately (my other endpoints are working ok with the changes)

GET
/fba/inventory/v1/summaries/
granularityId=A1F83G8C2ARO7P&granularityType=Marketplace&marketplaceIds=A1F83G8C2ARO7P&startDateTime=2020-01-01
content-type:application/json
host:sellingpartnerapi-eu.amazon.com
user-agent:amkapp/v1.0 (language=javascript)
x-amz-access-token:Atza|
x-amz-date:20201123T120830Z

content-type;host;user-agent;x-amz-access-token;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

**Comment by rogersv** [comment] 2020-11-23 12:58
The `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` indicates that you hashed an empty payload. You should not have a payload for this request

**Comment by ahlmackie** [comment] 2020-11-23 13:10
thanks, the guides indicate that if there is no payload, use a blank string:
https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html (point 6).
If I exclude this i get a 403 response: 'x-amzn-errortype': 'InvalidSignatureException'?

**Comment by JacksonJeans** [comment] 2020-11-23 13:13
@rogersv,
I would say that here the payload must be empty. There is no parameter to add to the `HTTPBody` at this API endpoint.
All parameters defined here in the documentation can be found in the query string: `Type: Query` . [Here](https://github.com/amzn/selling-partner-api-docs/blob/main/references/fba-inventory-api/fbaInventory.md#getinventorysummaries)

Here are some useful links to see what a payload really is in the HTTP protocol:
[HTTP (wiki)](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol)
[RFC7231(IETF)](https://tools.ietf.org/html/rfc7231)
[payloads of http request methods (StackOverflow)](https://stackoverflow.com/questions/5905916/payloads-of-http-request-methods)

With absolute probability the payload will be empty after the documentation. Or can someone here share a different experience especially about the `fba-inventory` API?

@ahlmackie, I'm sorry, in your case I don't know what to do.
If I am ready to work with the `fba-inventory` API, I will share my experience with you here.

**Comment by ahlmackie** [comment] 2020-11-23 13:20
thanks for you time @JacksonJeans I will let you know if I find the solution.  

I've raised a case with amazon to see if they can shed some light. Unfortunately is the very generic 403 response (similar to that people were recieving when having trouble with the STS token flow in the docs). I've put the JSON response and response headers below: 

response headers
{
  date: 'Mon, 23 Nov 2020 12:08:42 GMT',
  'content-type': 'application/json',
  connection: 'close',
  'x-amzn-requestid': '772305d1-5005-4d50-b83a-0fc6620ab98e',
  'x-amzn-errortype': 'AccessDeniedException',
  'x-amz-apigw-id': 'WdbrpG27DoEFXNQ='
}

response body:
  errors: [
    {
      message: 'Access to requested resource is denied.',
      code: 'Unauthorized',
      details: ''
  ]
}

**Comment by rogersv** [comment] 2020-11-23 13:21
Yes it should be empty. What I meant was "why is the "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" included in this request?".

**Comment by ahlmackie** [comment] 2020-11-23 13:26
@rogersv its just the final part of the string to be signed in the flow to calculate the signature...
https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html (point 6).
we were just checking the make up of the canonical request for errors

**Comment by ununu** [comment] 2020-11-30 17:18
I'm having the same problem.
Other endpoints mostly POST methods works fine, but this one returns "Unauthorized"

**Comment by ahlmackie** [comment] 2020-11-30 18:09
I had a message from amazon: they have identified an issue their end for this API and have notified the engineers. Hopefully resolved soon

**Comment by m4ciekm** [comment] 2020-12-10 10:41
Did they fix the problem? I'm also receiving the same message: "Access to requested resource is denied.", "code": "Unauthorized", whereas queries sent to "/orders/v0/orders" work without any issues.

**Comment by ahlmackie** [comment] 2020-12-10 13:58
had a response from amazon saying it is not available yet, no guidance on when they plan to take it live
I suspect Brexit has something to do with it

**Comment by winterstefan** [comment] 2020-12-21 20:35
_jfyi_, same scenario here:

- Trying to access SP-API (especially endpoint for fetching inventory)
- Constantly getting `HTTP 403` from the API
- Support just now replied that this use-case is not possible at the moment **the European marketplaces**

That reply came after a hell of a ride through various tickets and support requests. But I guess this information is final. At least the reply state that this official API documentation may be enhanced in order to clearly point out this fact. I did not hear information about if or when this use-case could be possible for EU.

**Comment by ahlmackie** [comment] 2020-12-22 12:59
I am also having trouble with the notifications API in europe - getting a 403 status code, though I have been assure it is working..?
@winterstefan are you able to access it?
@seanevan are we able to get some guidance on what APIs are active in each region?

**Comment by w2m** [comment] 2020-12-26 06:52
> Did they fix the problem? I'm also receiving the same message: "Access to requested resource is denied.", "code": "Unauthorized", whereas queries sent to "/orders/v0/orders" work without any issues.

I have the same problem. Diy you fix?

**Comment by paolofacchinetti** [comment] 2021-01-11 15:07
> _jfyi_, same scenario here:
> 
> * Trying to access SP-API (especially endpoint for fetching inventory)
> * Constantly getting `HTTP 403` from the API
> * Support just now replied that this use-case is not possible at the moment **the European marketplaces**
> 
> That reply came after a hell of a ride through various tickets and support requests. But I guess this information is final. At least the reply state that this official API documentation may be enhanced in order to clearly point out this fact. I did not hear information about if or when this use-case could be possible for EU.

Can someone from the dev team confirm this?
We've been developing on these APIs for a while and there's nothing at all in the documentation or any ufficial statement that confirms that the inventory APIs are not working for Europe.

If this is really the case, it's absolutely insane that there are **NO WARNINGS** about this, we're wasting our time building an application and we're stuck with 403 errors on getInventorySummaries calls.

**Comment by cohlar** [comment] 2021-01-16 19:42
I'm also interested to know when this endpoint will become available in Europe.

**Comment by Jethro-Wilkinson** [comment] 2021-01-20 09:42
Me too. Having the same issue.

**Comment by holger-core** [comment] 2021-02-17 13:26
Same Error Message;
"errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]

**Comment by ArmbrustR** [comment] 2021-03-12 11:21
Any news? any workarounds?
Is it possible to get /reports/{date}/reports?  -> I did try and got the same ErrorMessage

**Comment by danielbebbernovacode** [comment] 2021-04-23 11:03
Are there any updates on this issue? We are working on an application that relies on that endpoint.

**Comment by iamsr** [comment] 2021-04-29 09:12
The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network. Today this API is available only in the North America region. In 2021 we plan to release this API in the Europe and Far East regions.


It's for only NA region so if you are trying other than that it won't work.

**Comment by ahmetsametoglu** [comment] 2021-06-14 16:18
This is a very basic feature. I couldn't get the quantity of my fba_inventory. What is your plan for this feature?

**Comment by elrok1234** [comment] 2021-07-13 16:02
Can someone from Amazon please confirm if the sandbox endpoints of the `fba/inventory/v1/summaries` is working for north america marketplaces? I am receiving the same error as what a few people have described: 

- **Error**:
```
403 Forbidden
{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}
```
**My Sandbox Request**
`https://sandbox.sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries?details=true&granularityType=Marketplace&granularityId=ATVPDKIKX0DER&marketplaceIds=["ATVPDKIKX0DER"]`

**Authorization:** 
```
{{AccessKeyId}}
{{SecretAccessKey}}
us-east-1
execute-api
{{SessionToken}}
```

**Headers:**
```
Authorization
X-Amz-Date
X-Amz-Security-Token
Postman-Token
Host
User-Agent
Accept
Accept-Encoding
Connection
x-amz-access-token
```
Thanks in advance

**Comment by pbegle** [comment] 2021-07-16 21:44
I'm also getting a 403 error on this endpoint and I am in North America (US).

**Comment by iuzundal** [comment] 2021-07-17 16:46
Same problem

**Comment by shirushi-dev** [comment] 2021-07-20 14:43
Japanもです...😭

**Comment by okuson** [comment] 2021-07-31 06:32
Not released in Japan.
日本ではリリースされていません。

**Comment by Xfox1** [comment] 2021-08-01 18:41
Problem still present in Europe:

```
{ 
  code: 'Unauthorized',
  details: '',
  type: 'error'
}
```

**Comment by AmandeepSingh179** [comment] 2021-08-02 06:15
I am getting the same error for UK marketplace. Is there anyone who get this endpoint working?

**Comment by jkleupen** [comment] 2021-08-05 22:30
looks like they added the regional disclaimer back:  https://github.com/amzn/selling-partner-api-docs/commit/1db11640e9414e0604c5513c16a516dd891396a7

**Comment by kdursun** [comment] 2021-11-25 21:20
Problem still present in Europe:

{ 
  code: 'Unauthorized',
  details: '',
  type: 'error'
}

**Comment by kdursun** [comment] 2021-11-25 21:21
Problem still present in Europe:

{ 
  code: 'Unauthorized',
  details: '',
  type: 'error'
}
opened new case, waiting answer

**Comment by fedecarossino** [comment] 2021-12-08 19:44
@kdursun have you received an answer from amazon support??

**Comment by Gantonmaz** [comment] 2021-12-17 11:15
Has Amazon given a date as to when this might be available in the EU?

**Comment by nassuf** [comment] 2022-01-18 17:02
Hi there,
I have the same problem (eu marketplace).
Do you guys have found another way to get seller's products informations ?
Thanks !

**Comment by stokebob** [comment] 2022-02-14 11:57
I've contacted Amazon developer support on this, and they have confirmed that the endpoint is still only available in North America. They could not give an ETA of when it will be available in Europe, only that I should monitor the changelog on their new documentation site.

https://developer-docs.amazon.com/sp-api/changelog

**Comment by jlevers** [comment] 2022-02-21 05:44
That's strange, because I'm able to get _some_ data from Europe using this endpoint -- it's just not fully consistent. If I specify the UK marketplace ID, I seem to get back cumulative data for all the European marketplaces. If I specify a non-UK marketplace ID, I seem to get back cumulative data for all the European marketplaces _except_ the UK. If someone from Amazon could confirm what's actually going on here, that would be much appreciated.

cc @parvathm @ShivikaK

**Comment by rugved1991** [comment] 2022-05-10 04:50
Hi @jlevers @stokebob,

FBA Inventory API is available globally. Can you please test again and let us know if you are able to call the resource successfully?
If the issue persists, please open a support case and let us know the case ID.

Best,
Rugved
Solutions Architect, SP API

**Comment by jkleupen** [comment] 2022-05-18 11:45
Can confirm this is now working for EU.

**Comment by Xfox1** [comment] 2022-06-06 20:11
> 

Still not working for me (EU, Italy):

```
{
    "message": "Access to requested resource is denied.",
    "code": "Unauthorized",
    "details": "",
    "type": "error"
}
```

**Comment by bar2** [comment] 2022-08-01 13:55
@Xfox1 and other that might be having this issue, did you add "Product Listing" role to your application and re-authorized subject account that you are getting 403?

**Comment by raimundosilvac** [comment] 2022-08-02 20:21
Can someone here write an example of how to do the request to this endpoint in NodeJs? I've been trying to access to this endpoint but I have the following error:
```
CustomError: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
The Canonical String for this request should have been'GET/fba/inventory/v1/summariesDetails=true&MarketplaceIds=A1RKKUPIHCS9HS&granularityId=A1RKKUPIHCS9HS&granularityType=Marketplacehost:sellingpartnerapi-eu.amazon.comuser-agent:amazon-sp-api/0.7.9 (Language=Node.js/v12.18.3; Platform=Linux/4.4.0-19041-Microsoft)x-amz-access-token:<hashed-value>
The String-to-Sign should have been'AWS4-HMAC-SHA25620220802T192536Z20220802/eu-west-1/execute-api/aws4_request<hashed-value>'
```
My code is the following using amazon-sp-api on node:
```
let sellingPartner = new SellingPartnerAPI({
                region:'eu',
                refresh_token: '<my_refresh_token>',
                credentials:{
                    SELLING_PARTNER_APP_CLIENT_ID: "<MY_SELLING_PARTNER_APP_CLIENT_ID>",
                    SELLING_PARTNER_APP_CLIENT_SECRET: "<MY_SELLING_PARTNER_APP_CLIENT_SECRET>",
                    AWS_ACCESS_KEY_ID: "<MY_AWS_ACCESS_KEY_ID>",
                    AWS_SECRET_ACCESS_KEY: "<MY_AWS_SECRET_ACCESS_KEY>",
                    AWS_SELLING_PARTNER_ROLE: "<MY_AWS_SELLING_PARTNER_ROLE>",
                }        
            })
            let loadRequest = await sellingPartner.callAPI({
                operation:'getInventorySummaries',
                endpoint: 'fbaInventory',
                query: {
                    Details: true,
                    MarketplaceIds: [A1RKKUPIHCS9HS],
                    granularityType: "Marketplace",
                    granularityId: A1RKKUPIHCS9HS
                }
            });
```
Please, I don't know how to solve the error

**Comment by nothinman** [comment] 2022-10-15 22:10
@raimundosilvac did you manage to resolve this in the end?

**Comment by raimundosilvac** [comment] 2022-10-16 20:21
@nothinman yes i could!

**Comment by nothinman** [comment] 2022-10-16 21:36
> @nothinman yes i could!

Do you happen to remember what the issue was / how did you resolve it?
Been struggling for two days...

**Comment by ahmedfeki** [comment] 2022-11-15 22:23
I'm moving from MWS to SP-API in US as MWS will be deprecated in 2023 Dec
This problem the first i get after setting everything up  

MWS was great, SP API looks like it's an everyday nightmare  lol

**Comment by rugved1991** [comment] 2022-11-22 09:37
Hi @ahmedfeki,

If you are running into any issues, please feel free to open support case using this link: https://developer.amazonservices.com/support
If you come across any issue while implementing the SP API, please open a [GitHub issue](https://github.com/amzn/selling-partner-api-docs/issues). If you have any questions and need help or guidance from the developer community, please add a question on the [Discussion tab](https://github.com/amzn/selling-partner-api-docs/discussions).

Best,
Rugved
Solutions Architect, SP API.

**Closed by rugved1991** 2022-11-22 09:37 UTC
Labels: duplicate
