### ISSUE TITLE
Reports API reportTypes not taking multiple reportypes as Array of string

### ISSUE THREAD

**Issue by khanakia** [amzn/selling-partner-api-docs#768] opened 2021-05-23 15:16 UTC
**Describe the bug**
I want to return the data for multiple ReportTypes but this url only return data for one report type even i passed the multiple reportTypes
`https://sellingpartnerapi-eu.amazon.com/reports/2020-09-04/reports?marketplaceIds=A21TJRUUN4KGV&pageSize=100&reportTypes=GET_MERCHANT_LISTINGS_ALL_DATA&reportTypes=GET_FLAT_FILE_OPEN_LISTINGS_DATA`

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md#getreports

**Description of what the documentation currently says**
A list of report types used to filter reports  <string> Array

**Description of what the documentation should say**
How to pass the array of string to reportTypes ?

**Comment by johnkw** [comment] 2021-05-23 16:44
This is a duplicate of bug #356, and should be closed in favor of that bug, which definitely needs to get fixed.

This github has so many open bugs that it's hard to even find all the key bugs, but bug #356 is definitely up there.

**Closed** 2022-06-10 18:47 UTC
Labels: bug, Documentation, closed for inactivity
