### ISSUE TITLE
CreateDestination for ANY_OFFER_CHANGED_NOTIFICATION Bug

### ISSUE THREAD

**Issue by hkncnr07** [amzn/selling-partner-api-docs#1800] opened 2021-12-11 20:21 UTC
Hi,
We have an developer app.
Until yesterday, we were able to subscribe our customers' stores to ANY_OFFER_CHANGED_NOTIFICATION using the CreateDestination and CreateSubscribtion methods without encountering any problems.
However, now when we call the CreateDestination method, we get the following error:

{
"errors": [
{
"code": "Conflict",
"message": "The requested resource conflict with a resource in the server.",
"details": "A destination with arn arn:aws:sqs:us-east-1:xxxxxxx:xxx already exists for the application amzn1.sp.solution.xxxxxxxxxxxxxx"
}
]
}

I keep getting the same error even though I replaced the IAM Role, IAM User and IAM Policy data in my AWS account with the new ones.

Then I call GetDestionation method and I received:

{
"payload": [{"resource":{"sqs":{"arn":"arn:aws:sqs:us-east-2:xxxxxxxx:xxx"},"eventBridge":null},"destinationId":"xxxxxxxxxxxxxxxxxxx","name":"test"}]
}

As you see I only have 1 destination and couldnt create any new destination.
Then I try to delete the destination.
and received the response below:

{
"errors": [
{
"code": "Unauthorized",
"message": "The requested action is forbidden.",
"details": "Destination has subscriptions"
}
]
}

And I dont know which subscriptions I have.
How can I delete that destination? How can I get the subscriptions for that destination?
How can I add a new destination?

When I try to subscribe that destination it is succeed but got no notification.

There is a bug at api.
Could you please help us in short time? Our customers are waiting for that.

Thanks

I created a case at Seller Central for that and case ID: 9336193181

Thanks

**Comment by kpconnell** [comment] 2021-12-14 13:03
@hkncnr07 I spent a significant amount of time resolving this myself, as it turns out, you cannot create an additional subscription for the same type for the same seller within the same application.  Delete the prior subscription first, and the documentation here should reflect the error message and cause and this should be considered a [BUG] in the documentation

**Comment by farid-hussain-qbatch** [comment] 2021-12-29 13:15
I have got the same issue. @hkncnr07 How you have resolved it?

**Comment by farid-hussain-qbatch** [comment] 2021-12-30 07:26
@kpconnell @hkncnr07  I am having the same issue. kindly help me out. 
I am using different name with different ARN,but still getting the same error one creating the new destination.

**Comment by kpconnell** [comment] 2021-12-30 15:00
delete the old one first...

**Comment by iamricks** [comment] 2022-01-12 15:26
@kpconnell Did you have your original destination made through MWS? 

I have this same issue and i am fetching all the destinations and it's only showing that i have one although i had one made through MWS.

**Comment by kpconnell** [comment] 2022-01-12 16:30
This is a duplicate of #1850 and please open a case on this and put your case # in that thread.

Thanks

> @kpconnell Did you have your original destination made through MWS?
> 
> I have this same issue and i am fetching all the destinations and it's only showing that i have one although i had one made through MWS.

**Comment by zyf-123456** [comment] 2022-05-10 11:01
I meet a same question, help me

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Request has missing or invalid parameters and cannot be parsed.",
      "details": "No destination with id f6945728-50b3-44a0-92f0-e57a300413dc for applicationId 
           amzn1.sp.solution.3da9189a-2ff2-4e83-b#########"
    }
  ]
}

**Comment by zd6812282** [comment] 2022-10-19 06:37
订阅这个问题解决了么

**Closed** 2023-04-21 00:19 UTC
Labels: bug, Documentation, closing soon
