### ISSUE TITLE
x-amzn-RateLimit-Limit does not come in all responses.

### ISSUE THREAD

**Issue by kartman5** [amzn/selling-partner-api-docs#592] opened 2021-04-10 12:35 UTC
Hi,

I'm currently building my software new Amazon Selling Partner API.

I am calling OrderItem, OrderBuyerInfo, and OrderAddress API but I'm not getting x-amzn-RateLimit-Limit in the header.
How can I manage my Burst?

Thanks

**Comment by AmericanY** [comment] 2021-04-10 14:36
Hello @kartman5,

That's a good question. Kindly check the following [explaination](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md#the-x-amzn-ratelimit-limit-response-header) to better understand it.

![image](https://user-images.githubusercontent.com/27644047/114273551-c7fce900-9a1a-11eb-996e-e8f677caf059.png)

but if you would like to request it individually, Then you can do it via [that method](https://github.com/amzn/selling-partner-api-docs/blob/222f85708b65f9d2edbcbc3736887f679cba94ae/references/messaging-api/messaging.md#get-messagingv1ordersamazonorderid)

**Comment by charliecode** [comment] 2021-04-10 14:52
As weird and quirky as it may sound, follow what the [explanation](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md#the-x-amzn-ratelimit-limit-response-header) says and absolutely do not rely on that header. I honestly don't even know why they provide it, if it's not going to work consistently. It was the exact same thing with the MWS API. From my experience a far better approach is to focus your efforts on a retry exponential backoff strategy. Base it off the 429 status code as it will always be in the response and have fun building out the logic, it's tricky to get it right while also not needlessly waiting between requests.

**Comment by johnkw** [comment] 2022-04-16 20:30
This is a duplicate of https://github.com/amzn/selling-partner-api-docs/issues/86#issuecomment-911114383

**Closed** 2022-11-19 00:26 UTC
Labels: closing soon
